#!/usr/bin/env python3
"""
200 additional EAEP-style scenarios: licensing math, SAML/IWA/built-in design,
DR/restore, upgrade paths, distributed collaboration, Enterprise Builder/cloud,
hosted 3D / web layers / caching.

Domain weights on this 200-item segment: 34 / 18 / 22 / 26 %
=> 68 deploy, 36 troubleshoot, 44 maintain, 52 manage.

Tuples: (domainId, stem, correct, wrong1, wrong2, wrong3).

Distractor policy: eaep_distractor_design.py (on-domain wrong answers; plausible misconfigurations).
"""

from collections import Counter


def _q(domain, stem, c, w1, w2, w3):
    return (domain, stem, c, w1, w2, w3)


def get_extra_200_scenarios():
    rows = []
    d, t, m, g = (
        "deploy-enterprise",
        "troubleshoot-enterprise",
        "maintain-support-enterprise",
        "manage-content-users",
    )

    # --- Licensing & membership (52 manage) ---
    lic = [
        _q(
            g,
            "An organization currently assigns 30 Editor and 15 GIS Professional Standard user types. After a review, the new target is 10 Viewer, 40 Editor, and 20 GIS Professional Standard. Assuming no unused inventory, what additional licenses must procurement cover at minimum?",
            "Increase Viewer by 10, Editor by 10, and GIS Professional Standard by 5 compared to the prior peak assignment—compare per user type, not the sum of all numbers.",
            "Purchase exactly 70 new licenses because 10+40+20=70.",
            "No new licenses are needed because total headcount did not change.",
            "Buy only 5 licenses because the largest single-type increase is 5.",
        ),
        _q(
            g,
            "Portal shows 100 named users invited; 60 are active Editor types and 25 GIS Professional; finance approved 60 Editor and 25 GIS Professional entitlements. What is the licensing risk?",
            "Assignments must not exceed purchased entitlements per user type; over-assignment requires additional licenses or role changes.",
            "Portal automatically clips roles to available licenses without admin action.",
            "Named user counts are pooled across types so 85 total seats cover any mix.",
            "Inactive invites do not count toward license use.",
        ),
        _q(
            g,
            "A division adds 12 field workers needing Viewer capabilities only. Current Viewer entitlements are fully assigned. Editors have spare seats. Best administrative response?",
            "Acquire more Viewer entitlements or reassign roles so Viewer needs map to Viewer licenses—not Editor spare capacity.",
            "Map Viewers to Editor licenses because they are both named users.",
            "Use Primary Administrator Viewer licenses for all 12.",
            "Disable Viewer role entirely and use anonymous access.",
        ),
        _q(
            g,
            "The organization downgrades 20 users from GIS Professional to Editor. License server shows the same total count. What still must be true?",
            "Each user’s active user type must match an available entitlement of that type; downgrades free GIS Pro seats for reuse.",
            "Downgrades automatically return credits to ArcGIS Online.",
            "Editor and GIS Professional share one undifferentiated pool in Enterprise.",
            "License counts update only after reinstalling Portal.",
        ),
        _q(
            g,
            "Two portals in dev and prod each need 5 GIS Professional admins. The enterprise agreement lists 10 GIS Professional entitlements total. Can both environments be fully covered?",
            "Entitlements apply to the deployment; assigning the same 10 seats across two full sets of 5 typically requires 10 total only if users are not duplicated—not two independent full allocations unless 20 entitlements exist.",
            "Dev and prod always each receive duplicate entitlements automatically.",
            "Five entitlements split across environments is always enough.",
            "Licensing ignores non-production portals.",
        ),
        _q(
            g,
            "Add-on licenses (e.g., ArcGIS GeoAnalytics Server) are tied to GIS Professional users. You add GeoAnalytics for 10 specific analysts. What must align?",
            "Add-on assignment matches users with the correct base user type and add-on entitlements per Esri rules—not only portal group membership.",
            "Add-ons apply org-wide once purchased without per-user assignment.",
            "GeoAnalytics works for any Viewer without add-ons.",
            "Add-ons are tracked only in ArcGIS Online.",
        ),
        _q(
            g,
            "An audit finds 5 service accounts counted as GIS Professional named users. They run unattended scripts only. Best practice?",
            "Use appropriate licensing for automation (service accounts vs interactive users) per Esri guidance; avoid consuming interactive entitlements for machine accounts unnecessarily.",
            "Service accounts must always use GIS Professional.",
            "Named users cannot run scripts.",
            "Delete service accounts weekly.",
        ),
        _q(
            g,
            "The organization merges two departments. Portal membership shows 40 Editor assignments but only 35 Editor entitlements. What is the valid fix?",
            "Reduce assignments, purchase additional Editor entitlements, or temporarily adjust roles—licensing limits are hard caps for active assignments.",
            "Portal allows temporary 10% over-assignment.",
            "Merge groups to automatically free licenses.",
            "Delete the smaller department’s users without backup.",
        ),
        _q(
            g,
            "Users are imported from AD groups into default Viewer. Later, admins bulk-upgrade 50 to Editor without purchasing Editor seats. Symptom?",
            "Users may show Editor capabilities until license reconciliation fails or updates are blocked; align purchases before bulk role elevation.",
            "Bulk upgrade always succeeds without entitlements.",
            "AD group import ignores license types.",
            "Viewer and Editor use identical entitlements in Enterprise.",
        ),
        _q(
            g,
            "ArcGIS Pro is licensed through the portal. More Pro users than GIS Professional entitlements are invited. What breaks first?",
            "Pro sign-in and licensing align with portal user types and available entitlements; over-invitation without seats causes licensing errors for users.",
            "Pro ignores portal licensing.",
            "All Pro users share one floating license automatically.",
            "Entitlements apply only to web apps, not Pro.",
        ),
        _q(
            g,
            "Collaboration sends hosted layers to a partner org. Who consumes credits or licensing for analysis tools?",
            "Follow Esri rules for where the analysis runs and which org provisions premium capabilities—not only where the item originated.",
            "The host org never pays for partner analysis.",
            "Credits are always split 50/50.",
            "Collaboration disables all licensing checks.",
        ),
        _q(
            g,
            "A custom role grants publishing without GIS Professional. Users cannot publish hosted layers. Why?",
            "Publishing hosted layers typically requires a user type that includes hosting privileges (often Creator/GIS Professional family)—custom roles cannot override user type ceilings.",
            "Publishing requires only the custom role name.",
            "Hosted layers use anonymous publishing.",
            "Publishing is controlled solely by group names.",
        ),
        _q(
            g,
            "The license file is updated mid-year with more GIS Professional seats. Portal still shows old limits. First step?",
            "Import/update the license file in Portal and verify the portal reflects new entitlements; restart if documented.",
            "Reinstall ArcGIS Server.",
            "Delete all users and re-import.",
            "Licenses update from Active Directory sync.",
        ),
        _q(
            g,
            "Trial expirations: some users show ‘expired’ user type though the org renewed. Cause?",
            "Verify license file dates, portal system settings, and that users were not left on deprecated trial assignments.",
            "Trials extend automatically on payment.",
            "Expiration is based on Windows time zone only.",
            "Delete browser cache on the license server.",
        ),
        _q(
            g,
            "Org policy: max 200 Editors. Current 195. Project onboards 10 Editors next month. What must happen before go-live?",
            "Procure additional Editor entitlements or adjust role plan before assignment exceeds 200.",
            "Portal rounds down extra users silently.",
            "Use Viewer accounts for editing in emergencies.",
            "Editors can share one seat by shift rotation without license impact.",
        ),
        _q(
            g,
            "Floating concurrent use is not in use; all licensing is named user through the portal. What is true about Pro on two machines?",
            "Named user terms still apply; concurrent use rules differ from perpetual concurrent licensing—follow current Esri user-type rules for the deployment.",
            "Named users may always run five simultaneous sessions.",
            "Floating and named user are interchangeable.",
            "Pro checks only the local license file.",
        ),
        _q(
            g,
            "A user has GIS Professional and an add-on for Insights. Insights is removed from the add-on list. User still opens Insights. Likely?",
            "Cached tokens or grace periods may apply; verify license reconciliation and remove access per updated entitlements.",
            "Add-ons persist forever once assigned.",
            "Insights does not require licensing in Enterprise.",
            "Remove Insights by deleting the hosting server.",
        ),
        _q(
            g,
            "Department A funds 20 Editor seats; Department B funds 10. Central IT assigns all 30 in one portal. Governance question?",
            "Track allocation vs. usage by business unit; portal admin still ensures total assignments do not exceed purchased entitlements.",
            "Each department portal is required for split billing.",
            "Funding model changes Esri enforcement.",
            "B’s seats cannot be used for A’s users.",
        ),
        _q(
            g,
            "Users removed in AD still appear licensed in portal for 24 hours. Risk?",
            "Delayed sync may temporarily hold seats; use portal disable/remove workflows aligned with security policy for faster revocation.",
            "AD removal instantly frees all licenses always.",
            "Licenses follow AD tombstones forever.",
            "Portal ignores AD deletes.",
        ),
        _q(
            g,
            "Education site: student accounts cycle each semester. Licensing concern?",
            "Recycle or reclaim named user assignments for churn; avoid orphan accounts consuming entitlements.",
            "Student accounts are free in Enterprise.",
            "Semester rollover deletes portal automatically.",
            "Use one shared student login for compliance.",
        ),
        _q(
            g,
            "Org wants exactly 5 GIS Professional users for a pilot. 20 users are in the GIS Professionals group in AD. After sync, portal tries to assign all 20. Fix?",
            "Scope sync filters or portal group membership so only intended users receive GIS Professional—not unfiltered AD groups.",
            "Portal caps at 5 automatically.",
            "GIS Professional is assigned alphabetically.",
            "Remove AD to fix licensing.",
        ),
        _q(
            g,
            "Dual-use: same person has accounts in two enterprises for testing. Licensing pitfall?",
            "Each named user in each deployment consumes entitlements in that deployment; do not assume shared seats across separate license servers.",
            "One Enterprise license covers unlimited portals.",
            "Test users are exempt.",
            "Duplicate emails merge licenses.",
        ),
    ]
    rows.extend(lic)

    collab = [
        _q(
            g,
            "In distributed collaboration, a **parent** workspace sends hosted feature layers to a **child** participant. Edits in the child do not appear in the parent workspace. What should be checked first?",
            "Sync direction and supported sync types for the workspace (send vs receive); not all collaborations are bidirectional for all item types.",
            "Parent and child always sync in real time for every layer.",
            "Delete collaboration and use email exports.",
            "Hosted layers cannot participate in collaboration.",
        ),
        _q(
            g,
            "A **guest** workspace receives updates from a host. Schedule is daily. Stakeholders expect hourly. What must change?",
            "Adjust the collaboration sync schedule and verify workload limits—not only ‘collaboration exists’.",
            "Change schedule to every second in all cases.",
            "Hourly requires ArcGIS Online only.",
            "Guest workspaces cannot receive edits.",
        ),
        _q(
            g,
            "Two agencies use different coordinate systems. Collaboration syncs features but geometry looks shifted in the guest org. Likely issue?",
            "Transformation and spatial reference handling between orgs; validate CRS assumptions—not only portal sharing.",
            "Collaboration ignores spatial reference.",
            "Rely on on-the-fly datum transformations in the guest org without validating source and target CRS in the workspace.",
            "Export shared layers to shapefile for both agencies to avoid enterprise geodatabase CRS metadata.",
        ),
        _q(
            g,
            "Workspace A is linked to multiple guest orgs. One guest sees deletes, another does not. Explanation?",
            "Each guest connection has its own workspace settings and allowed operations; configure per guest relationship.",
            "All guests inherit the same behavior automatically.",
            "Deletes never sync.",
            "First guest wins exclusively.",
        ),
        _q(
            g,
            "Legal holds prevent deleting features in Org B. Org A deletes the same feature. What might happen?",
            "Policy and collaboration rules may block or diverge delete propagation; technical sync meets governance boundaries.",
            "Deletes always propagate regardless of law.",
            "Collaboration bypasses legal holds.",
            "The host org retains final authority over all deletion operations for collaborated items in both orgs.",
        ),
        _q(
            g,
            "Attachments are not appearing for collaborated line layers though geometry syncs. Common configuration gap?",
            "Attachment sync depends on enabled capabilities and supported item types for the collaboration workspace.",
            "Attachments always sync with geometry automatically.",
            "Enable attachments on the email server.",
            "Collaboration strips attachments for performance.",
        ),
        _q(
            g,
            "After changing the host portal URL, guest orgs show disconnected collaboration. Fix?",
            "Update collaboration endpoints and re-establish trust per migration procedures; invitations embed URLs.",
            "Guests auto-follow DNS CNAMEs without admin steps.",
            "Delete all guest users.",
            "Collaboration ignores portal URL changes.",
        ),
        _q(
            g,
            "A workspace is set to send-only from host to guest. Guest editors need to push edits back. What is required?",
            "A bidirectional or appropriate send/receive workspace design for those layers—not a one-way send-only link.",
            "Change group owner to primary admin.",
            "Send-only can be overridden by group tags.",
            "Use email for return edits.",
        ),
        _q(
            g,
            "Multiple workspaces exist between the same two orgs for different programs. Risk?",
            "Operational complexity and duplicate sync; document which workspace owns which content to avoid conflicting updates.",
            "Esri allows only one workspace globally.",
            "Second workspace disables the first.",
            "Workspaces merge automatically.",
        ),
        _q(
            g,
            "Collaboration shows ‘sync failed’ for one layer only. Others succeed. First focus?",
            "That item’s schema, size, attachments, or permissions—not the whole collaboration connection.",
            "Restart Portal for all failures.",
            "Delete the collaboration.",
            "Reinstall ArcGIS Server.",
        ),
        _q(
            g,
            "Parent/child terminology: which statement matches typical Esri usage in docs?",
            "‘Host’ and ‘participant’ orgs use workspaces with defined send/receive roles; understand your org’s configured direction per layer type.",
            "Parent always means ArcGIS Online.",
            "Child orgs cannot own items.",
            "Parent and child refer only to Active Directory.",
        ),
        _q(
            g,
            "Guest org disables the collaboration user account. Symptom?",
            "Sync failures for operations requiring that identity; align service accounts or guest access policy.",
            "Host automatically creates replacement users.",
            "Collaboration uses anonymous access silently.",
            "Disable is ignored until reboot.",
        ),
        _q(
            g,
            "Firewall opens 443 between orgs; sync still fails with timeouts on large replicas. Next step?",
            "Scale timeouts, schedule off-peak, or reduce payload; 443 open does not guarantee performance for bulk sync.",
            "Open all TCP ports 1–65535.",
            "Disable HTTPS compression.",
            "Move collaboration to FTP.",
        ),
        _q(
            g,
            "Org wants one-way publication of authoritative boundaries to many guests without receiving edits. Pattern?",
            "Configure send-only workspaces to each guest with appropriate content groups—not bidirectional defaults.",
            "Bidirectional is mandatory.",
            "Use public sharing instead of collaboration.",
            "One workspace cannot target multiple guests.",
        ),
        _q(
            g,
            "Versioning conflicts appear on collaborated layers edited in both orgs. Expectation?",
            "Distributed editing requires reconciliation workflows; collaboration does not remove geodatabase concurrency rules.",
            "Last saved always wins silently.",
            "Versioning is disabled in collaboration.",
            "Conflicts mean collaboration is broken.",
        ),
        _q(
            g,
            "Item owner in host org leaves. Guest copies stop updating. Related factor?",
            "Ownership transfer and sharing on host items used in the workspace; guests depend on valid host items.",
            "Guests retain independent copies forever without host.",
            "Delete protection blocks collaboration permanently.",
            "Collaboration ignores ownership.",
        ),
        _q(
            g,
            "Testing collaboration in a staging portal with production URLs copied. Risk?",
            "Wrong endpoints and trust; use staging-specific URLs and clean workspace definitions.",
            "Staging always isolates automatically.",
            "URLs are cosmetic.",
            "Copying content directory copies collaboration trust.",
        ),
        _q(
            g,
            "An admin establishes distributed collaboration between two agencies to share maps and hosted layers. After the first sync completes, web maps appear in the guest org but several Survey123 forms and Insights workbooks are absent. What is the most likely explanation?",
            "Follow current Esri documentation for supported items; some apps or data types have partial or no sync.",
            "Every item type syncs fully at all versions.",
            "PDF attachments are the only content type that syncs completely across all collaboration workspace versions.",
            "Hosted feature layers are the only item type that propagates attribute edits in real time during sync.",
        ),
        _q(
            g,
            "Guest org uses a different identity store than host. Challenge?",
            "User mapping and trust are at the item/org level; identity mismatch does not merge accounts automatically across orgs.",
            "AD trust is required for collaboration.",
            "Guests must use built-in accounts only.",
            "SAML prevents collaboration.",
        ),
        _q(
            g,
            "Collaboration metrics show latency increasing quarter over quarter. Action?",
            "Review data growth, network path, and sync schedule; plan capacity—not only initial connectivity success.",
            "Latency is constant forever.",
            "Delete old replicas without archive policy.",
            "Disable monitoring.",
        ),
    ]
    rows.extend(collab)

    # --- Auth: SAML, IWA, built-in (68 deploy total for segment; auth is part of deploy) ---
    auth = [
        _q(
            d,
            "An organization deploys ArcGIS Enterprise for staff. Active Directory backs accounts. A corporate SAML SSO platform with MFA is already integrated with AD and used by many apps. Users include domain-joined desktops, mobile/tablet users, and remote users on non-domain devices. Goal: consistent SSO and MFA across apps. Which pattern best fits?",
            "SAML-based enterprise logins in Portal (with built-in accounts only for exceptions)—aligning with the existing IdP and MFA while supporting diverse clients via standard SAML/OAuth flows.",
            "IWA plus built-in only—covers all non-domain mobile and remote scenarios without extra design.",
            "IWA plus SAML simultaneously for all users without Web Adaptor planning.",
            "Built-in accounts only to maximize MFA coverage.",
        ),
        _q(
            d,
            "Same scenario, but leadership mandates IWA for office users and refuses SAML. Remote and mobile users must still authenticate. Best compromise?",
            "IWA for browsers that support it on domain-joined machines plus SAML or token-based flows for other clients—not IWA alone for everyone.",
            "IWA alone works on all mobile devices with default settings.",
            "Disable remote users.",
            "Use anonymous access for mobile.",
        ),
        _q(
            d,
            "Portal is configured with SAML enterprise logins. A vendor app uses OAuth to Portal. Where do MFA prompts typically appear?",
            "At the IdP during SAML/OAuth sign-in when MFA is enforced—Portal consumes the assertion/token from the IdP.",
            "MFA is enforced only inside ArcGIS Pro settings.",
            "Portal ignores IdP MFA.",
            "MFA applies only to built-in accounts.",
        ),
        _q(
            d,
            "IWA is enabled on the Web Adaptor. Python scripts using the REST API get 401. Browsers work. Explanation?",
            "Scripts do not perform interactive Kerberos negotiation; use token/OAuth or configured service accounts for unattended access.",
            "Enable IWA for Python by installing a browser on the server.",
            "Disable HTTPS on REST.",
            "Scripts must use the primary admin password only.",
        ),
        _q(
            d,
            "Built-in accounts are required for a few external consultants. Enterprise logins cover staff. What is a sound design?",
            "Use SAML for enterprise users and controlled built-in accounts where justified—with clear governance—not duplicate identities casually.",
            "Merge built-in and SAML usernames automatically.",
            "Built-in cannot coexist with SAML.",
            "Consultants must use AD only.",
        ),
        _q(
            d,
            "SAML NameID is email in test and UPN in production IdP. Portal shows duplicate identities after cutover. Prevention?",
            "Coordinate attribute mapping and a single stable NameID strategy before go-live.",
            "Portal merges duplicates nightly.",
            "Use email only for all SAML.",
            "Delete production IdP.",
        ),
        _q(
            d,
            "IWA works internally; external users hit SAML through the same portal URL. What must the Web Adaptor and DNS support?",
            "Clear separation or order of auth handlers and reachable URLs for internal vs external paths per Esri patterns—not a single undifferentiated IWA for all.",
            "IWA applies to external users automatically.",
            "Two portal installations are mandatory.",
            "External users must use VPN only.",
        ),
        _q(
            d,
            "Mobile SAML login fails with redirect_uri mismatch after adding a new load-balanced hostname. Cause?",
            "OAuth redirect URIs registered for the portal OAuth app must include every hostname clients use.",
            "Mobile ignores OAuth.",
            "Load balancers do not affect SAML.",
            "Disable MFA for mobile.",
        ),
        _q(
            d,
            "An agency wants a single authentication method covering Portal browser access, ArcGIS Pro, and field mobile apps. The network team proposes IWA at the Web Adaptor to avoid managing SAML metadata. What is the key limitation of this approach?",
            "IWA alone for every client and scenario—non-domain and non-Windows clients require different flows.",
            "SAML with OAuth apps.",
            "Built-in with strong passwords.",
            "SAML with PKCE for mobile.",
        ),
        _q(
            d,
            "Portal allows disabling built-in accounts. When is that appropriate?",
            "When all users are provisioned through enterprise logins and policy forbids local accounts—after validating break-glass access plans.",
            "Always on day one without testing.",
            "Never; built-in cannot be disabled.",
            "Disabling built-in removes SAML.",
        ),
        _q(
            d,
            "Kerberos delegation is required for some services behind IWA. Who configures SPNs?",
            "AD and service account administrators in coordination with Esri Web Adaptor/IWA documentation—not only the GIS team guessing.",
            "Portal generates SPNs automatically.",
            "SPNs are only for databases.",
            "Disable delegation for security.",
        ),
        _q(
            d,
            "SAML assertion contains groups but Portal roles do not update. Check?",
            "Portal claim mapping and group/role rules; assertion must include claims Portal is configured to map.",
            "Groups cannot pass through SAML.",
            "Restart clients only.",
            "SAML groups override AD.",
        ),
        _q(
            d,
            "Built-in primary admin vs enterprise admin recovery: why keep break-glass?",
            "IdP outages or SAML misconfiguration can lock enterprise users out; a controlled built-in or recovery path is operational resilience.",
            "Break-glass violates security always.",
            "Primary admin is optional.",
            "SAML never fails.",
        ),
        _q(
            d,
            "Hybrid: some apps use OAuth confidential, others public. Portal supports both. Risk to avoid?",
            "Embedding client secrets in public apps or repos—use correct OAuth app types and redirect URIs.",
            "All apps should be confidential.",
            "Public apps cannot use Portal.",
            "OAuth is only for Pro.",
        ),
        _q(
            d,
            "IWA through Web Adaptor and an upstream reverse proxy. 401 for some paths. Likely?",
            "Kerberos hop/proxy configuration: clients, SPNs, and constrained delegation across proxies per documentation.",
            "Disable reverse proxy.",
            "Use HTTP for IWA.",
            "IWA does not work with Web Adaptor.",
        ),
        _q(
            d,
            "SAML metadata refresh job fails silently; certs expire next week. Mitigation?",
            "Monitor IdP metadata and cert expiry; process to update portal SAML config before rollover.",
            "SAML certs never expire.",
            "Disable SAML weekly refresh.",
            "Portal pulls new certs without config.",
        ),
        _q(
            d,
            "Tablet browsers use SAML; native app uses OAuth. Same user sees different MFA behavior. Why?",
            "Different clients and OAuth vs browser SAML flows may interact with IdP policies differently—coordinate IdP app registrations.",
            "Portal controls MFA prompts exclusively.",
            "Native apps skip MFA always.",
            "Tablets cannot use SAML.",
        ),
        _q(
            d,
            "LDAP sync vs SAML: LDAP is used for group membership, SAML for login. Valid pattern?",
            "Yes—directory sync can populate groups while authentication uses SAML assertions, when configured per Esri guidance.",
            "LDAP and SAML cannot coexist.",
            "Choose one identity technology total.",
            "LDAP replaces SAML login.",
        ),
        _q(
            d,
            "Anonymous access enabled for public maps alongside SAML staff maps. Security design note?",
            "Layer and app sharing must still enforce which layers are public vs authenticated—anonymous does not secure private layers.",
            "Anonymous overrides SAML.",
            "Public maps imply all layers public.",
            "Disable SAML when anonymous is on.",
        ),
        _q(
            d,
            "IWA prompts disappear after a GPO change. Suspect?",
            "Browser integrated Windows auth settings, trusted sites, and Kerberos settings—not Portal alone.",
            "Reinstall Portal.",
            "Delete Web Adaptor.",
            "Disable enterprise logins.",
        ),
    ]
    rows.extend(auth)

    builder_cloud = [
        _q(
            d,
            "An admin uses **ArcGIS Enterprise Builder** for a base deployment on Windows. Which statement is most accurate?",
            "Enterprise Builder orchestrates installation/configuration steps for a supported base pattern; complex multi-site or Linux patterns may use other installers or manual steps per documentation.",
            "Enterprise Builder is the only supported method for every Enterprise topology.",
            "Enterprise Builder deploys only to Linux.",
            "Enterprise Builder skips the data store.",
        ),
        _q(
            d,
            "Deploying Portal on **AWS** using CloudFormation templates from Esri: what should you still validate?",
            "IAM, networking, DNS, TLS, and data paths match your security model—not only launching the stack.",
            "CloudFormation replaces all security planning.",
            "AWS deployments need no data store.",
            "Portal on AWS cannot federate Server.",
        ),
        _q(
            d,
            "Azure **managed disks** vs blob for content: consideration for Portal?",
            "Performance, backup, and mount semantics for supported configurations; follow Esri’s cloud reference architectures.",
            "Blob is always the content directory.",
            "Azure forbids ArcGIS Server.",
            "Use only serverless functions for Portal.",
        ),
        _q(
            d,
            "Kubernetes / container story for ArcGIS Enterprise: general admin takeaway?",
            "Follow current Esri product statements for which components are container-supported and how ops differ from Windows/Linux VMs—not assumptions from generic K8s apps.",
            "Everything runs in pods by default today without docs.",
            "Kubernetes replaces Web Adaptor always.",
            "Containers eliminate need for data store.",
        ),
        _q(
            d,
            "Cloud **egress** costs spike for tile requests. Mitigation?",
            "CDN, caching, and architecture to reduce cross-region pulls—not only blaming Portal CPU.",
            "Disable HTTPS to save egress.",
            "Move database to email.",
            "Delete tile layers.",
        ),
        _q(
            d,
            "Enterprise Builder creates a deployment; patching later: who owns order?",
            "Follow Esri patch compatibility matrices and order for Portal, Server, and Data Store—not random partial patches.",
            "Builder locks versions forever.",
            "Patch Linux first always.",
            "Enterprise Builder’s built-in updater patches Portal; Server and Data Store must be patched independently.",
        ),
        _q(
            d,
            "Lift-and-shift VMs to cloud: licensing consideration for ArcGIS?",
            "Ensure deployment still complies with license terms for cloud/virtualized hosts and license manager connectivity if used.",
            "Cloud removes all licensing.",
            "VMs need no license manager ever.",
            "Esri Cloud license is automatic with AWS account.",
        ),
        _q(
            d,
            "S3-backed stores for caches: admin must verify?",
            "IAM policies, endpoints, and Server account access from all site nodes—not only portal admin rights.",
            "S3 works without credentials.",
            "S3 is only for backups.",
            "Disable encryption for performance.",
        ),
        _q(
            d,
            "Multi-AZ vs single-AZ for Portal VM: DR implication?",
            "Multi-AZ improves availability within a region but does not replace backup/restore discipline for Portal and data stores.",
            "Multi-AZ means zero RPO.",
            "Single-AZ is always cheaper with same SLA.",
            "AZ failure requires no recovery plan.",
        ),
        _q(
            d,
            "Cloud load balancer health checks hit Portal REST. 200 OK but users see errors. Issue?",
            "Health checks may not validate full dependency chain (data store, search); deepen health probes or monitoring.",
            "If LB is green, stop investigating.",
            "LB causes Portal errors always.",
            "Remove federated servers.",
        ),
        _q(
            d,
            "Using **Cloud Enterprise Builder** (if offered in your release) vs manual: benefit?",
            "Repeatable, documented topology for supported cloud images—still requires customer networking and identity integration.",
            "Cloud Builder needs no DNS.",
            "Cloud Builder configures SAML automatically for all IdPs.",
            "Cloud Builder is only for ArcGIS Online.",
        ),
        _q(
            d,
            "Object storage for backups off-site: WebGISDR output to cloud bucket. Check?",
            "Permissions, lifecycle, and encryption for the bucket; validate restore paths from cloud to on-prem if needed.",
            "Buckets are automatically immutable.",
            "WebGISDR only writes to local disk.",
            "Cloud backup needs no restore test.",
        ),
    ]
    rows.extend(builder_cloud)

    layers_3d = [
        _q(
            d,
            "A **hosted scene layer** is published from a scene layer package. Fine LODs are missing in Scene Viewer though coarse levels draw. Tile cache data store is healthy. Likely class of issue?",
            "Scene cache generation or truncation at high LODs—space, time, or process failure partway through the pyramid.",
            "Relational data store collation.",
            "Portal search index only.",
            "Disable WebGL.",
        ),
        _q(
            d,
            "**Vector tile** service updates weekly; clients still see old tiles. Besides Portal, what layer often caches?",
            "CDN, browser, reverse proxy, or intermediate tile caches—invalidate or version URLs per your architecture.",
            "Vector tiles cannot be cached.",
            "ArcGIS Pro caches vector tiles locally; clearing the Pro project cache resolves all stale tile issues.",
            "Restart Portal only.",
        ),
        _q(
            d,
            "**Cached map service** built from a map service; dynamic layer works. Cache shows stale edits. Expected?",
            "Cached tiles reflect the build time; refresh cache or use dynamic layers for real-time edits—understand update modes.",
            "Cache auto-updates on every edit.",
            "Delete dynamic capability always.",
            "Edits appear in cache without rebuild.",
        ),
        _q(
            d,
            "**Hosted feature layer** with **dependent hosted scene layer**; scene fails when republishing features. Check?",
            "Rebuild order and dependencies between feature and scene caches; scene may need rebuild after schema or extent changes.",
            "Scene layers never depend on features.",
            "Republish without deleting scene.",
            "Disable feature layer.",
        ),
        _q(
            d,
            "**Elevation** service HTTPS mixed content in Scene Viewer. Symptom?",
            "Browser blocks HTTP elevation on HTTPS pages; align HTTPS endpoints and certificates.",
            "Elevation uses relational store only.",
            "Disable Scene Viewer.",
            "Use HTTP for portal to match.",
        ),
        _q(
            d,
            "**3D object / multipatch** layers slow on integrated GPU. Admin angle?",
            "Client hardware guidance and layer complexity; not solely a Server tuning knob.",
            "Increase Server instances to fix GPUs.",
            "Disable 3D org-wide.",
            "Object layers must be dynamic only.",
        ),
        _q(
            d,
            "**Web scene** saved in Portal references layers from two federated servers. One server is down. Behavior?",
            "Partial scene content fails; resilience depends on layer availability and error handling in apps.",
            "Portal merges layers automatically.",
            "Web scene copies all data locally.",
            "Federation hides server failures.",
        ),
        _q(
            d,
            "**Scene layer** with global extent and local project; performance issues. Tuning?",
            "Extent, clipping, and LOD limits appropriate to use case—not full globe detail everywhere.",
            "Increase LODs to maximum always.",
            "Scene layers ignore extent.",
            "Use shapefile for global scenes.",
        ),
        _q(
            d,
            "**Map image layer** cache vs **tile layer** for basemap: trade-off?",
            "Tiles optimize predictable basemaps; map image layer may be better for frequently changing symbology or dynamic layers per needs.",
            "Always use tiles for everything.",
            "Map image cannot cache.",
            "Tiles always update live.",
        ),
        _q(
            d,
            "**Hosted web layer** print vs export: server-side output folder permissions differ from Pro. Issue class?",
            "Server account permissions and print gp service—not only portal item sharing.",
            "Print uses desktop profile paths.",
            "Disable HTTPS for print.",
            "Tiles control print fonts.",
        ),
        _q(
            d,
            "**Vector tile** style update; apps show old style. Cause?",
            "Style resource caching in apps/CDN; bump cache keys or clear caches per client stack.",
            "Styles cannot change after publish.",
            "Vector tiles embed styles in Portal DB only.",
            "Restart relational data store.",
        ),
        _q(
            d,
            "**Scene service** from enterprise GDB vs hosted: DR consideration?",
            "Enterprise paths and credentials must be valid in DR; hosted may restore differently via relational/tile stores.",
            "Both restore identically from one folder copy.",
            "Hosted ignores backups.",
            "Enterprise GDB needs no registration in DR.",
        ),
        _q(
            d,
            "**LOD** mismatch: mobile clamps scale; desktop shows detail. Factor?",
            "Client max scale / LOD exposure settings and tiling scheme alignment.",
            "LOD is server-only.",
            "Mobile always matches desktop.",
            "Fix by changing CSV encoding.",
        ),
        _q(
            d,
            "**Web layer** item deleted; web map still references it. User impact?",
            "Broken layer in map until republished/relinked—dependency integrity at item level.",
            "Portal auto-replaces deleted layers.",
            "Web maps ignore broken layers silently always.",
            "Delete web map automatically.",
        ),
        _q(
            d,
            "**Cached map service** on NAS with high latency. Symptom?",
            "Slow tile read under pan/zoom; storage performance matters for caches.",
            "NAS cannot host caches.",
            "Latency affects only Pro.",
            "Move cache to email attachments.",
        ),
        _q(
            d,
            "**Hosted 3D** and **drone mesh** large uploads; portal item limits. Admin action?",
            "Understand hosted storage limits, object store, and chunking; may require alternative publishing paths.",
            "Portal has unlimited upload size.",
            "Mesh must use shapefile.",
            "Disable HTTPS for large uploads.",
        ),
        _q(
            d,
            "**Feature service** with pop-ups; **WFS** still exposes attributes. Lesson?",
            "Control OGC/WFS capabilities and service security—not only pop-up configuration.",
            "WFS follows pop-up visibility only.",
            "Disable REST to fix WFS.",
            "OGC is view-only always.",
        ),
        _q(
            d,
            "**Scene layer** shared to group; elevation not shared. Symptom?",
            "Terrain may fail for users without access to elevation dependency layers.",
            "Scene ignores elevation permissions.",
            "Share scene only; elevation follows automatically always.",
            "Disable terrain globally.",
        ),
    ]
    rows.extend(layers_3d)

    # More deploy items to reach 68: add 6 more auth/edge (deploy)
    rows.extend(
        [
            _q(
                d,
                "Federation admin URL uses internal DNS; public OAuth clients use external DNS. Token validation fails for some APIs. Focus?",
                "Consistent URL strategy for admin, services, and OAuth redirects across internal/external contexts.",
                "Use internal DNS for all clients.",
                "Disable OAuth for APIs.",
                "Merge DNS zones without testing.",
            ),
            _q(
                d,
                "Web Adaptor on Windows; Portal on Linux. Supported?",
                "Follow Esri-supported combinations for your versions; mixed OS is common with Web Adaptor per documented matrix—not assumed impossible.",
                "Web Adaptor must match Portal OS exactly.",
                "Linux cannot run Portal.",
                "Windows Web Adaptor cannot proxy Linux Portal.",
            ),
            _q(
                d,
                "SSL offloading at LB: health checks OK but OAuth state lost. Why?",
                "Sticky sessions or correct headers for OAuth state/affinity where required by your topology.",
                "OAuth is stateless always.",
                "Disable load balancing.",
                "Use HTTP between LB and WA.",
            ),
            _q(
                d,
                "Portal **Web Context URL** vs **privatePortalURL** style settings: why both concepts exist?",
                "Separate internal vs external access patterns; set per Esri guidance for your network design.",
                "They must always be identical strings.",
                "privatePortalURL is deprecated always.",
                "Web Context URL and privatePortalURL must always be set to identical values in any supported deployment.",
            ),
            _q(
                d,
                "ArcGIS Server **cluster** with two machines; one GPU for raster rendering. Consideration?",
                "Assign raster-intensive workloads aware of which machines run which instances; not all nodes are interchangeable for GPU.",
                "GPU is automatically load-balanced across all services.",
                "Clusters require identical hardware.",
                "Disable raster on Server.",
            ),
            _q(
                d,
                "**Image layer** from mosaic dataset; cache build vs dynamic. Choice?",
                "Cached for predictable performance; dynamic when data changes frequently or caching is impractical.",
                "Mosaic datasets cannot cache.",
                "Dynamic is always faster.",
                "Cache removes all pyramids.",
            ),
        ]
    )

    # --- Troubleshoot (36): DR / blank maps / symptoms ---
    dr_sym = [
        _q(
            t,
            "After a full DR restore per the documented backup workflow, Portal and federated servers are healthy, databases connect, and REST returns 200. A high-performance **basemap cache** now returns blank tiles at all scales while the service stays started. **Most** likely root cause?",
            "The recovery did not restore or rebuild **service-derived caches** (tile cache) or their paths/credentials even though the service definition exists—cached tiles are often separate from platform DB restores.",
            "Transactional inconsistency in the enterprise GDB alone—without cache symptoms.",
            "Federation trust is broken because REST returned 200.",
            "The enterprise geodatabase was not referenced at all.",
        ),
        _q(
            t,
            "Post-restore, **dynamic** map image layers draw, but **cached** map services are blank. Logs clean. First suspicion?",
            "Missing, empty, or wrong-path tile cache data or access from the server account—not the map document alone.",
            "Federation must be recreated always.",
            "Database collation is wrong.",
            "Blank cached tiles after restore indicate the portal search index is out of sync with the tile cache data.",
        ),
        _q(
            t,
            "DR site uses different file paths for cache directories. Services start. Tiles blank. Fix class?",
            "Update cache directory configuration or restore data to expected paths with correct permissions.",
            "Reinstall Portal completely.",
            "Delete federation.",
            "Point cache directories at production UNC paths in DR without updating registrations or permissions.",
        ),
        _q(
            t,
            "Restore omitted **tile cache data store** files but relational store is current. Hosted **scene** draws coarse but not fine LODs. Likely?",
            "Incomplete tile/scene cache data for high LODs in the tile cache store—not only relational consistency.",
            "Scene layers do not use tile cache.",
            "Relational store controls all LODs.",
            "Disable WebGL.",
        ),
        _q(
            t,
            "Backup software skipped large cache folders ‘to save time.’ DR test shows fast maps except one county basemap. Cause?",
            "Incomplete backup of that cache or partial files—validate backup scope includes all cache locations referenced by services.",
            "County basemaps cannot be cached.",
            "Portal controls county boundaries.",
            "The mosaic dataset clip boundary excludes that county; fix cartography in Pro, not backup scope.",
        ),
        _q(
            t,
            "RPO for caches is 24h; relational is 1h. After incident, features are newer than tiles. User perception?",
            "Spatial mismatch between features and older tiles until caches rebuild—explain expected behavior and rebuild caches.",
            "Users never notice tile age.",
            "Features auto-update tiles instantly always.",
            "Disable feature layers.",
        ),
        _q(
            t,
            "After restore, **fonts** missing on server; labels print blank. Dynamic layers?",
            "Server-side font installation for the print/GP context—not only portal theme.",
            "Fonts are only in Pro.",
            "Disable labels globally.",
            "Reinstall clients only.",
        ),
        _q(
            t,
            "HTTPS inspection re-enabled after DR; OAuth works in browser but scripts fail. Same as before DR?",
            "Trust chain for automation may differ from interactive flows; re-apply exclusions or trust for script hosts.",
            "Scripts never use TLS.",
            "Disable inspection entirely without policy.",
            "OAuth is unrelated to TLS.",
        ),
        _q(
            t,
            "GeoEvent outputs stall after restore though services are started. Check?",
            "Kafka/spatiotemporal or output connection strings and credentials in the DR network.",
            "GeoEvent ignores DR.",
            "Restart Portal only.",
            "Delete all feeds.",
        ),
        _q(
            t,
            "Notebook Server kernels cannot reach data paths that worked pre-failure. DR difference?",
            "UNC paths, DNS, and permissions for the Notebook run-as account in DR—not only portal availability.",
            "Notebook uses portal database for files.",
            "Disable notebooks in DR.",
            "Copy notebooks to USB.",
        ),
        _q(
            t,
            "Load balancer sticky sessions lost after migration; Portal admin UI flaky. Related?",
            "Stateful admin flows may need affinity or correct headers—validate LB configuration for Portal.",
            "Admin UI is stateless always.",
            "Disable load balancer.",
            "Use HTTP for admin.",
        ),
        _q(
            t,
            "Raster tile service shows color ramp shift after restore. Suspect?",
            "Different GDAL/env or raster proxy settings between old and new hosts—not only the mosaic dataset path.",
            "Rasters ignore environment.",
            "Shift is always monitor calibration.",
            "Reinstall ArcGIS Pro on users.",
        ),
        _q(
            t,
            "WMS GetMap works; REST map image layer fails for same service. Focus?",
            "Different code paths or authentication between OGC and REST; check security and endpoints.",
            "WMS and REST are identical internally always.",
            "Disable OGC.",
            "Delete REST endpoint.",
        ),
        _q(
            t,
            "Scene Viewer WebGL errors after GPU driver update on clients. Admin role?",
            "Client software/hardware guidance; communicate supported browsers and drivers—not a server patch alone.",
            "Update Server GPU drivers only.",
            "Disable Scene Viewer org-wide.",
            "Scene requires ArcGIS Online.",
        ),
        _q(
            t,
            "Intermittent 500 from hosting server when publishing hosted layers after partial restore. Likely?",
            "Incomplete relational or tile data store state vs portal expectations—validate stores and logs.",
            "500 means Web Adaptor only.",
            "Disable publishing forever.",
            "Redeploy only the Web Adaptor and ignore relational or tile data store validation after the partial restore.",
        ),
        _q(
            t,
            "Edge cache still serves old vector tiles after service update. Not Server REST cache. Next?",
            "Purge CDN/edge or version the service URL—coordinate with network team.",
            "Vector tiles never cache at edge.",
            "Delete Portal content.",
            "Disable HTTPS.",
        ),
        _q(
            t,
            "Hosted feature layer query times out; DB metrics normal. App layer?",
            "Large result sets, client timeouts, or service maxRecordCount—not only DB CPU.",
            "DB metrics tell the whole story always.",
            "Set maxRecordCount to unlimited always.",
            "Disable query capability.",
        ),
        _q(
            t,
            "Printing hosted layers: legend symbols differ from web map. Cause class?",
            "Font and server-side symbol resources vs web rendering—not only sharing.",
            "Legends are identical always.",
            "Print ignores fonts.",
            "Disable legends in service.",
        ),
        _q(
            t,
            "GPServer works in Pro; fails on Server with same data on DR SAN. Check?",
            "SAN permissions and path visibility for the Server account—same as interactive user tests.",
            "Pro and Server always share credentials.",
            "SAN cannot host GIS data.",
            "Copy data to C: on server.",
        ),
        _q(
            t,
            "Metadata search finds items but thumbnails 404 after migration. Likely?",
            "Content directory or static resource paths not fully migrated or URL base changed.",
            "Thumbnails live in the database only always.",
            "Search index replaces files.",
            "Disable thumbnails.",
        ),
        _q(
            t,
            "Collaboration sync errors only for large attachments. Others OK. Focus?",
            "Payload size, timeout, or storage limits for attachments in sync—not the whole collaboration link.",
            "Attachments cannot sync ever.",
            "Raise only the map’s minimum scale in the web map so attachments skip sync.",
            "Delete collaboration.",
        ),
        _q(
            t,
            "Portal **living atlas** layers fail after DR; enterprise layers work. Cause?",
            "External dependency availability and portal utility service configuration for online layers—not your DB restore.",
            "Living Atlas is in your content directory.",
            "Disable utility services.",
            "Restore Living Atlas from backup.",
        ),
        _q(
            t,
            "CPU low, disk queue high on cache volume during map use. Symptom?",
            "Storage throughput bottleneck for tile reads—not CPU scaling first.",
            "Add Portal machines.",
            "Delete tile cache.",
            "Disable monitoring.",
        ),
        _q(
            t,
            "Intermittent blank tiles without errors in logs. Suspect?",
            "Race at cache generation, antivirus locking files, or storage glitches—investigate correlated events.",
            "Blank tiles mean federation failure always.",
            "Logs capture every cache miss always.",
            "Regenerate the entire map cache globally at peak load to replace missing tiles.",
        ),
        _q(
            t,
            "Service extension vs core: custom SOE throws after upgrade. First step?",
            "Extension compatibility with new Server version and recompile/redeploy per developer docs.",
            "Uninstall Data Store.",
            "Disable custom SOEs permanently.",
            "Rollback Windows only.",
        ),
    ]
    rows.extend(dr_sym)

    # --- Maintain (44): upgrade + backup ---
    up_bk = [
        _q(
            m,
            "Upgrading **10.9.1 → 11.x** (illustrative): which mindset matches Esri guidance?",
            "Follow the published upgrade path, compatibility matrix, and order for Portal, Server, Data Store, and Web Adaptor for your target release—no skipping unsupported jumps.",
            "Always upgrade Server before Portal regardless of matrix.",
            "Skip Data Store if relational is healthy.",
            "Upgrade production first without staging.",
        ),
        _q(
            m,
            "Upgrade requires a new **Web Adaptor** version matching Server. Forgot WA. Symptom?",
            "Client connectivity or supported protocol mismatch—install the correct Web Adaptor build for the upgraded site.",
            "Web Adaptor auto-upgrades with Portal.",
            "Web Adaptor version does not matter.",
            "Use port 6080 publicly to bypass WA.",
        ),
        _q(
            m,
            "Relational data store minor version mismatch with Portal after upgrade attempt. Risk?",
            "Supported combinations only; bring relational store to compatible version per matrix.",
            "Minor mismatch is always safe.",
            "Relational store never upgrades.",
            "Delete relational and recreate without backup.",
        ),
        _q(
            m,
            "Geodatabase upgrade required for newer Server. Order?",
            "Typically validate backups, upgrade GDB per DBMS and Esri steps, then validate services—not ad hoc on production Friday.",
            "Upgrade GDB before backup.",
            "Skip GDB upgrade; Server tolerates it.",
            "Use Access for enterprise GDB.",
        ),
        _q(
            m,
            "Portal upgrade stuck on search reindex. Action?",
            "Allow time, verify disk and logs; follow troubleshooting for index rebuild—not power off mid-upgrade.",
            "Reboot servers randomly.",
            "Delete search index files during upgrade.",
            "Skip search forever.",
        ),
        _q(
            m,
            "ArcGIS Server **patches** released; Portal not patched yet. Policy?",
            "Maintain supported version skew windows; patch per documented order and test.",
            "Patch Server only always.",
            "Patches are optional for security.",
            "Never patch Data Store.",
        ),
        _q(
            m,
            "Upgrade testing in staging: minimum fidelity?",
            "Representative data, auth, and integrations—not only version numbers matching.",
            "Staging can be empty databases always.",
            "Hardware irrelevant for upgrade tests.",
            "Skip federated servers in staging.",
        ),
        _q(
            m,
            "Python **arcpy** version tied to Pro/Server upgrade. Developer impact?",
            "Scripts may need testing and environment updates for new arcpy/Python stacks.",
            "arcpy never changes between versions.",
            "Python 2 scripts run unchanged forever.",
            "Disable arcpy in Enterprise.",
        ),
        _q(
            m,
            "Database OS upgrade (Windows/SQL) before Enterprise upgrade. Sequence?",
            "Validate Esri support for DB/OS versions with target Enterprise; test combined matrix.",
            "OS upgrade cannot affect ArcGIS.",
            "Always upgrade Enterprise before OS.",
            "SQL upgrades require Linux Portal.",
        ),
        _q(
            m,
            "Rollback after failed upgrade: what must exist?",
            "Tested backups and documented rollback that includes DB, content, and stores—not only VM snapshot assumptions.",
            "Rollback is always a reinstall from scratch.",
            "Snapshots replace DB backup always.",
            "Delete backups before upgrade to save space.",
        ),
        _q(
            m,
            "Upgrade changes portal item schema; custom apps break. Mitigation?",
            "Test apps against staging API changes; follow deprecation notices.",
            "Portal guarantees no breaking API changes ever.",
            "Custom apps are unsupported.",
            "Disable HTTPS for APIs.",
        ),
        _q(
            m,
            "Notebook Server upgrade: special consideration?",
            "Notebook Server images and conda env compatibility per release notes.",
            "Notebook Server upgrades with Notepad.",
            "Delete all notebooks before upgrade.",
            "Notebook Server is optional always.",
        ),
        _q(
            m,
            "Image Server upgrade with mosaic caches. Step?",
            "Validate cache rebuild needs and disk after upgrade—follow release guidance.",
            "Caches never need rebuild.",
            "Delete mosaics before upgrade.",
            "Image Server cannot upgrade in place.",
        ),
        _q(
            m,
            "GeoEvent upgrade with spatiotemporal data store. Check?",
            "Compatibility and upgrade order for GeoEvent with Server and data stores per documentation.",
            "GeoEvent upgrades independently always.",
            "Delete spatiotemporal data.",
            "GeoEvent requires ArcGIS Online.",
        ),
        _q(
            m,
            "SSL cert renewal during upgrade window. Coordination?",
            "Renew and validate trust before or during upgrade to avoid auth failures mid-cutover.",
            "Certs never affect upgrades.",
            "Use self-signed for upgrade week only.",
            "Disable TLS during upgrade.",
        ),
        _q(
            m,
            "Multi-machine site: rolling upgrade vs full stop. Guidance?",
            "Follow Esri rolling upgrade steps for multi-machine Server when available for your version—not ad hoc node-by-node.",
            "Upgrade one random machine first always.",
            "All machines must be offline simultaneously always.",
            "Clone VMs instead of upgrade.",
        ),
        _q(
            m,
            "Portal **reindex** after version jump. Why?",
            "Search index format or endpoints may change; rebuild per upgrade doc.",
            "Reindex is cosmetic always.",
            "Delete all items before reindex.",
            "Search rebuilds automatically without admin.",
        ),
        _q(
            m,
            "License file for new version. Action?",
            "Obtain and apply current license file for the upgraded deployment version.",
            "Old license works forever after upgrade.",
            "Licenses are only in ArcGIS Online.",
            "Delete license manager.",
        ),
        _q(
            m,
            "Prohibited jump: two major versions in one night. Risk?",
            "Unsupported paths and longer outage; plan staged upgrades per matrix.",
            "Esri supports any jump with enough coffee.",
            "Data store prevents jumps automatically.",
            "Backup is unnecessary for skipped versions.",
        ),
        _q(
            m,
            "Post-upgrade: hosted layers OK, **Insights** fails. Suspect?",
            "Insights deployment compatibility and licensing with new Portal—validate Insights version matrix.",
            "Insights is part of Portal always.",
            "Uninstall Insights to fix Portal.",
            "Insights requires only CSV.",
        ),
        _q(
            m,
            "Backup before upgrade: WebGISDR **and** DB native backup. Why both?",
            "Different restore stories: platform bundle vs granular DB recovery—follow RTO/RPO design.",
            "One method always suffices.",
            "WebGISDR replaces SQL backup always.",
            "DB backup is illegal for Enterprise.",
        ),
        _q(
            m,
            "Incremental DB backups between full WebGISDR. Consistency?",
            "Understand recovery points: platform restore may need matching DB point-in-time.",
            "Incrementals cannot be restored.",
            "WebGISDR includes all DB history automatically.",
            "Skip transaction log backups.",
        ),
        _q(
            m,
            "Restore test quarterly but only file share, not DB. Gap?",
            "Cannot validate end-user workflows without database consistency with portal items.",
            "File share proves DB health.",
            "DB restore is never needed.",
            "Test only Portal URL.",
        ),
        _q(
            m,
            "Encrypted backups; key lost. Outcome?",
            "Backups are unrecoverable—key management is part of DR.",
            "Esri can decrypt without key.",
            "Disable encryption for DR.",
            "Keys are embedded in Portal.",
        ),
        _q(
            m,
            "Cross-region restore: latency breaks synchronous workflows. Expectation?",
            "Adjust architecture or app expectations; DR geography affects UX.",
            "Latency is zero in cloud.",
            "Move users to the DR region physically.",
            "Disable editing in DR.",
        ),
        _q(
            m,
            "Automation: backup job overlaps with WebGISDR. Symptom?",
            "Resource contention and longer windows—schedule non-overlapping or scaled resources.",
            "Jobs never overlap.",
            "WebGISDR is instant.",
            "Delete automation.",
        ),
        _q(
            m,
            "Restore to newer hardware: driver differences affect raster. Test?",
            "Validate raster rendering and performance on new hosts.",
            "Hardware never affects GIS.",
            "Raster is CPU-only.",
            "Skip testing if Portal starts.",
        ),
        _q(
            m,
            "Item IDs after cross-portal migration scripts. Issue?",
            "IDs change; update apps and references—not raw copy expecting same IDs.",
            "IDs are globally unique forever.",
            "Copy content dir preserves IDs across portals.",
            "Apps auto-map old IDs.",
        ),
        _q(
            m,
            "Log retention post-incident: legal hold on logs. Backup impact?",
            "Storage growth and immutability requirements—plan retention policies.",
            "Logs do not grow.",
            "Delete logs before incident closes.",
            "Legal hold disables backups.",
        ),
        _q(
            m,
            "Patch SQL for vulnerability; Esri matrix says unsupported combo temporarily. Choice?",
            "Delay SQL patch or coordinate Esri patch window—do not leave unsupported combo in prod long.",
            "SQL patches always safe first.",
            "Unsupported combo is fine for weeks.",
            "Disable Portal until SQL patches.",
        ),
        _q(
            m,
            "Zero-downtime goal for upgrade; single server deployment. Honest statement?",
            "True zero downtime requires HA architecture; single machine has maintenance windows.",
            "Maintenance mode hides all downtime.",
            "Zero downtime is always achievable.",
            "Use DNS round-robin on one machine.",
        ),
    ]
    rows.extend(up_bk)

    # --- Fill to 200 (68/36/44/52): +12 d, +11 t, +13 m, +10 g ---
    rows.extend(
        [
            _q(
                d,
                "Federated Image Server **upgrade**: mosaic overviews incomplete after upgrade. Action?",
                "Rebuild overviews or rerun caching per release notes—validate raster pipeline after upgrade.",
                "Delete mosaic datasets.",
                "Upgrade skips rasters always.",
                "Disable Image Server.",
            ),
            _q(
                d,
                "**Portal WebAdaptor** name vs DNS CNAME for OAuth: users bookmark CNAME. Risk?",
                "OAuth redirect URIs and portal URLs must include every client-facing hostname.",
                "CNAME is invisible to OAuth.",
                "Bookmarks bypass SAML.",
                "Disable CNAME.",
            ),
            _q(
                d,
                "**ArcGIS Enterprise on Kubernetes** (if used in your org): ops difference from VMs?",
                "Follow Esri’s container release notes for scaling, upgrades, and persistence—not generic Kubernetes defaults alone.",
                "K8s removes need for data store.",
                "No ingress configuration required.",
                "Portal runs in serverless only.",
            ),
            _q(
                d,
                "**Spatiotemporal big data store** alongside relational: backup implication?",
                "Include all registered data stores in coordinated backup/DR plans—not only relational.",
                "Spatiotemporal needs no backup.",
                "One folder copy backs up all stores.",
                "Disable spatiotemporal for DR.",
            ),
            _q(
                d,
                "**GeoAnalytics Server** federated: where do tools execute?",
                "On the GeoAnalytics Server resources per architecture—not on Portal machines by default.",
                "Always on the database server.",
                "GeoAnalytics tools always execute on the Portal machine when GeoAnalytics Server is federated.",
                "GeoAnalytics tools execute in ArcGIS Online by default even when Enterprise is licensed for GeoAnalytics.",
            ),
            _q(
                d,
                "**Utility services** (routing, geocode) in portal org settings: why set region-appropriate endpoints?",
                "Licensing, latency, and data residency—defaults may not match your region or agreement.",
                "Utilities are global with no choice.",
                "Utilities bypass authentication.",
                "Set utilities only in Pro.",
            ),
            _q(
                d,
                "**Reverse proxy** path-based routing to Portal vs Server: common mistake?",
                "Incomplete forwarding for Portal static assets, admin API, or WebSockets—follow Esri proxy patterns.",
                "Path routing never breaks Portal.",
                "Use one path for all REST.",
                "Disable admin API externally.",
            ),
            _q(
                d,
                "**Read replicas** for enterprise GDB: map services read-only to replica. Publishing consideration?",
                "Editing services must point to primary/writable registration; read replicas for scale-out reads only.",
                "Replicas accept edits by default.",
                "Portal picks primary automatically always.",
                "Replicas replace backups.",
            ),
            _q(
                d,
                "**ArcGIS Monitor** alerts on disk for cache volumes: proactive step?",
                "Capacity planning and cleanup before full disks break publishing—not reactive only.",
                "Disk alerts mean delete relational store.",
                "Monitor replaces backups.",
                "Ignore until 100% full.",
            ),
            _q(
                d,
                "**Portal language/locale** vs date fields in hosted layers: user confusion?",
                "Client locale and field formatting; not a server ‘bug’—communicate expectations.",
                "Server forces US locale always.",
                "Disable localization.",
                "Delete hosted layers.",
            ),
            _q(
                d,
                "**SDE command** or direct DB edit bypassing ArcGIS while services run: risk?",
                "Can corrupt versions and service state—use supported edit paths.",
                "SDE commands are always safe.",
                "Services detect all DB edits instantly.",
                "Disable versioning.",
            ),
            _q(
                d,
                "**Multiple Web Adaptors** to one Portal for different URLs: supported use?",
                "Possible with correct configuration; OAuth redirects must list all client entry points.",
                "A Portal can support at most one Web Adaptor per machine; additional WAs require separate IIS instances.",
                "Second WA breaks federation always.",
                "Use different portals instead.",
            ),
            _q(
                t,
                "After restore, **symbol** fonts in vector tile style differ from authoring. Cause?",
                "Font availability in server/renderer vs authoring workstation—not only the tile package.",
                "Vector tiles embed all fonts always.",
                "Styles cannot change.",
                "Reinstall Portal.",
            ),
            _q(
                t,
                "**Intermittent** token refresh in long-running web workers. Developer fix?",
                "Implement refresh token or periodic re-auth per OAuth patterns—not infinite access tokens.",
                "Set token lifetime to infinite.",
                "Disable HTTPS for workers.",
                "Use primary admin token.",
            ),
            _q(
                t,
                "**Antivirus** real-time scan locks cache files during tile generation. Symptom?",
                "Partial tiles or corrupt cache—exclude paths per Esri guidance.",
                "AV never touches caches.",
                "Disable all security.",
                "Move cache to USB.",
            ),
            _q(
                t,
                "**Mixed EPSG** in web map: one layer wrong CRS. Scene fails?",
                "Layer spatial reference must align with scene/map requirements—validate layer CRS.",
                "Portal auto-reprojects all cases perfectly.",
                "Disable Scene Viewer.",
                "Use only WGS84 web maps.",
            ),
            _q(
                t,
                "**Hosted feature layer** attachment upload fails; features edit OK. Check?",
                "Object store or attachment settings and size limits—not the feature DB only.",
                "Attachments use relational only always.",
                "Disable HTTPS for uploads.",
                "Attachments require ArcGIS Online.",
            ),
            _q(
                t,
                "**Map service** maxRecordCount low; dashboard charts incomplete. Fix?",
                "Raise within sensible limits or summarize server-side—not only portal filters.",
                "maxRecordCount is fixed at 1000 forever.",
                "Charts ignore limits.",
                "Delete dashboard.",
            ),
            _q(
                t,
                "**Portal** home page custom JavaScript errors after upgrade. Cause?",
                "Unsupported or deprecated JS APIs—update custom code to current portal JS API.",
                "Portal bans all JavaScript.",
                "JavaScript runs only in Pro.",
                "Reinstall browsers.",
            ),
            _q(
                t,
                "**Federated server** clock skew vs Portal. Symptom?",
                "Token or trust validation failures—sync time (NTP) across tiers.",
                "Clock skew is ignored by OAuth.",
                "Disable time sync.",
                "Set all clocks to UTC only without NTP.",
            ),
            _q(
                t,
                "**Database** connection pooling exhausted during morning peak. GIS sees?",
                "Query timeouts and generic errors—tune pool and DB resources, not only Portal CPU.",
                "Pooling is unlimited always.",
                "Disable connection pooling.",
                "Add Portal RAM only.",
            ),
            _q(
                t,
                "**Custom widget** CORS errors to Portal. Fix?",
                "Configure allowed origins or proxy per security policy—not disabling CORS globally without analysis.",
                "CORS is off by default always.",
                "Allow * for all origins in prod.",
                "Disable HTTPS.",
            ),
            _q(
                t,
                "**Scene layer** works in Pro but not in Scene Viewer. Check?",
                "HTTPS, WebGL, and layer URL accessibility from browser—not Pro’s engine only.",
                "Scene Viewer cannot host scene layers.",
                "Pro and Viewer use identical stacks always.",
                "Disable scene layers.",
            ),
            _q(
                m,
                "**Read replica** failover: GDB promoted to primary. ArcGIS?",
                "Update connection strings/registrations to the new writable endpoint and validate services.",
                "ArcGIS auto-follows DB promotion always.",
                "Replicas need no reconfiguration.",
                "Delete all services.",
            ),
            _q(
                m,
                "**Tomcat** (if used) or WA JVM heap for heavy traffic: tuning?",
                "Follow Esri guidance for Web Adaptor/container memory—not unbounded heap growth.",
                "Heap should be minimal always.",
                "JVM is not used by Web Adaptor.",
                "Set heap to 1 MB.",
            ),
            _q(
                m,
                "**Portal content directory** move to new volume: documented steps include?",
                "Configuration update, file copy consistency, and reindex/search considerations per Esri—not only robocopy.",
                "Move folder and restart Windows only.",
                "Content dir can split across USB drives.",
                "Delete search before move.",
            ),
            _q(
                m,
                "**ArcGIS Server** **directories** move: what must stay coherent?",
                "Config store, directories, and machine records per multi-machine guidance.",
                "Copy directories without stopping services.",
                "Each machine uses different config store paths.",
                "Directories are optional.",
            ),
            _q(
                m,
                "**PostgreSQL** vacuum/maintenance during GIS peak: impact?",
                "IO contention—schedule with DBAs off-peak for large tables used by services.",
                "VACUUM blocks all reads always.",
                "GIS should run VACUUM manually hourly.",
                "Disable autovacuum.",
            ),
            _q(
                m,
                "**SQL Server** tempdb on slow disk; GP scratch heavy. Effect?",
                "GP performance drops—storage tuning for tempdb per DBA best practices.",
                "tempdb is never used by ArcGIS.",
                "Move tempdb to email.",
                "GP ignores temp space.",
            ),
            _q(
                m,
                "**Certificate** chain incomplete on internal CA; browsers trust via GPO but Java processes do not. Impact?",
                "GeoEvent, certain connectors, or Java-based tools may fail TLS until trust is in the right store.",
                "Java uses browser trust always.",
                "Disable internal CA.",
                "Install cert on clients only.",
            ),
            _q(
                m,
                "**Maintenance mode** banner in Portal: use case?",
                "Communicate planned outage or read-only window—not a substitute for HA.",
                "Maintenance mode upgrades software automatically.",
                "Blocks all logins forever until uninstall.",
                "Maintenance mode replaces backups.",
            ),
            _q(
                m,
                "**Snapshot** of VM while ArcGIS services running: backup validity?",
                "Crash-consistent image may not replace application-consistent backup for databases—follow Esri/DB vendor guidance.",
                "VM snapshot is always enough for GDB.",
                "Snapshots never work for GIS.",
                "Snapshot replaces WebGISDR always.",
            ),
            _q(
                m,
                "**Firewall** rule change blocks Server-to-DB during upgrade window. Symptom?",
                "Service start failures or query errors after upgrade steps—validate rules before declaring success.",
                "Firewall cannot affect localhost connections.",
                "Upgrade opens all ports temporarily.",
                "Disable firewall for upgrades.",
            ),
            _q(
                m,
                "**Content replication** lag between primary and DR file shares. Risk?",
                "Stale items or missing files at DR cutover—RPO for file sync must match DR objectives.",
                "Replication is always synchronous.",
                "DR uses live primary files always.",
                "File lag does not affect Portal.",
            ),
            _q(
                m,
                "**Manual** schema change in hosted layer without client testing. Downstream?",
                "Apps and maps may break—use staged schema change processes.",
                "Portal auto-fixes all apps.",
                "Schema changes are invisible to REST.",
                "Delete all web maps on change.",
            ),
            _q(
                m,
                "**Patch** antivirus DAT update quarantines a DLL under ArcGIS Server. Response?",
                "Restore file, add exclusion per Esri AV guidance, validate services—not permanent disable.",
                "Reinstall Windows.",
                "Delete quarantine permanently.",
                "Run Server as Administrator.",
            ),
            _q(
                g,
                "**Group** limits: maximum groups per org policy. Hitting limit. Options?",
                "Consolidate groups, archive unused, or request policy exception—technical limits are real.",
                "Unlimited groups always.",
                "Delete random groups weekly.",
                "Merge orgs without planning.",
            ),
            _q(
                g,
                "**StoryMaps** vs **Web AppBuilder** ownership transfer when author leaves. Issue?",
                "Apps depend on items and accounts; transfer ownership and update credentials per policy.",
                "StoryMaps auto-transfer to admin.",
                "Apps have no dependencies.",
                "Delete author account immediately.",
            ),
            _q(
                g,
                "**Survey123** integration with Enterprise: licensing nuance?",
                "Survey123 capabilities may depend on user types and extensions—verify current Esri documentation for your version.",
                "Survey123 is free with any Viewer.",
                "Surveys never use credits.",
                "Survey123 requires ArcGIS Online only.",
            ),
            _q(
                g,
                "**Experience Builder** app points to dev portal URLs in prod. Fix?",
                "Update app item URLs and OAuth registrations for production endpoints.",
                "Experience Builder auto-detects prod.",
                "URLs are embedded in code only.",
                "Disable Experience Builder.",
            ),
            _q(
                g,
                "**Tracker for ArcGIS** with Enterprise: deployment note?",
                "Follow product requirements for hosting and licensing with your Enterprise version—not assumed identical to Online-only docs.",
                "Tracker needs no server.",
                "Tracker uses only shapefiles.",
                "Disable location services.",
            ),
            _q(
                g,
                "**Knowledge Graph** (if applicable) with Enterprise: admin concern?",
                "Resource sizing and supported topologies per release—validate against Esri docs for your deployment.",
                "Knowledge Graph replaces portal search.",
                "No graph database needed.",
                "Install on USB only.",
            ),
            _q(
                g,
                "**Batch geocoding** credit-like usage in Enterprise: governance?",
                "Assign roles and monitor usage; understand what your deployment meters.",
                "Batch geocoding is unlimited in Enterprise.",
                "Geocoding ignores roles.",
                "Disable geocoding for security.",
            ),
            _q(
                g,
                "**Insights for ArcGIS** with spatiotemporal data: prerequisite?",
                "Compatible data stores and licensing for Insights features per documentation.",
                "Insights reads only CSV.",
                "Spatiotemporal blocks Insights always.",
                "Insights installs on Portal only without data store.",
            ),
            _q(
                g,
                "**ArcGIS Dashboards** embedded in a public site: what must be true for viewers?",
                "Dashboard, layers, and dependent items must be visible to the intended audience.",
                "Dashboard sharing implies all layers are public automatically.",
                "Public dashboards ignore HTTPS requirements.",
                "Disable dependent layers for performance.",
            ),
            _q(
                g,
                "**Year-end** license true-up: procurement counts differ from portal assignments. What is the correct process?",
                "Reconcile portal role assignments with purchased entitlements and correct discrepancies before closing books.",
                "Audits never cover Enterprise licensing.",
                "Delete users until counts match without documentation.",
                "The license file syncs automatically from accounting systems.",
            ),
        ]
    )

    c = Counter(r[0] for r in rows)
    assert sum(c.values()) == 200, len(rows)
    assert c[d] == 68, c
    assert c[t] == 36, c
    assert c[m] == 44, c
    assert c[g] == 52, c
    return rows
