#!/usr/bin/env python3
"""
100 additional “case study” style EAEP scenarios: layered constraints, plausible distractors.

Distractor policy: eaep_distractor_design.py (wrong options stay in the same technical domain as the stem).

Note: Inspired by case-study practice style; the ChatGPT share link could not be fetched programmatically.

Domain weights on this segment: 34 / 18 / 22 / 26 % => 34 / 18 / 22 / 26 questions.

Returned tuples: (domainId, stem, correct, wrong1, wrong2, wrong3).
"""


def _row(domain, stem, correct, w1, w2, w3):
    return (domain, stem, correct, w1, w2, w3)


def get_extra_100_case_study_scenarios():
    rows = []

    # --- Deploy (34) ---
    d = "deploy-enterprise"
    rows += [
        _row(d, "A regional utility uses split DNS: internal users resolve an internal portal hostname; external users use a public FQDN. After cutover, OAuth mobile clients intermittently return redirect_uri errors. Web Adaptor TLS matches the public name. What should you validate first?", "OAuth app redirect URIs and portal public URL / WebContextURL settings for each hostname clients actually use—not only the Web Adaptor certificate SAN.", "Reinstall Portal on the DMZ only.", "Disable split DNS and merge zones without a plan.", "Map every user to the primary admin account."),
        _row(d, "A water district federated a second ArcGIS Server for raster analytics. Image services publish, but creating hosted web layers still fails validation though a hosting server is assigned. Before blaming the raster site, what should you verify?", "That the hosting server path, data store registration, and publishing account can satisfy hosted layer workflows—not only federated raster capability.", "Unregister the hosting server.", "Install Portal on the raster machine.", "Disable HTTPS on the raster site."),
        _row(d, "A defense contractor’s SAML IdP sits in a DMZ. Classified workstations cannot reach the IdP’s external metadata URL; lab users can. Logins fail on classified machines. What is the core issue?", "IdP endpoints and metadata must be reachable from every required client network; use internal IdP aliases or split metadata—not a single external-only discovery path.", "Delete SAML and use anonymous access.", "Lower TLS to 1.0 for classified subnets.", "Disable Portal firewall rules entirely."),
        _row(d, "Notebook Server jobs that arcpy.read file shares fail with path not found, while the same UNC works in Pro on an analyst desktop. Interactive notebook test on Server succeeds when data is copied local. What should you check first?", "The Notebook Server run-as account has OS permissions and stable UNC resolution to registered paths—not the analyst’s interactive profile.", "Reinstall Notebook on the analyst PC.", "Disable UNC and use C:\\\\users paths on the server.", "Delete the relational data store."),
        _row(d, "GeoEvent writes to hosted feature services. After a DR exercise the geodatabase moved subnets; feeds show ‘connected’ but counts flatline. Services start. What should you reconcile?", "Database connectivity, registration, and firewall paths from GeoEvent/Server to the DB at its new address—including service account reachability.", "Reinstall GeoEvent without testing connections.", "Disable feature services and use CSV exports only.", "Increase tile cache size on Portal."),
        _row(d, "A multi-machine Server site uses a load-balanced Web Adaptor. One node was rebuilt with a new hostname and rejoined without Esri’s documented join procedure. The site is inconsistent. Best next step?", "Remove the misjoined machine cleanly and rejoin per Esri multi-machine guidance so config store and cluster state stay coherent.", "Copy config folders between random servers.", "Run two sites with one config store path.", "Ignore hostname changes."),
        _row(d, "Hosted scene layer caches stall at high LODs; hosting machine disks show free space and relational store is green. What should you inspect next?", "Tile cache / scene cache data store health, permissions, and capacity for deep pyramids—not only OS free space on C:.", "Delete the scene service.", "Move Portal to another domain.", "Set all map services to a single instance."),
        _row(d, "An enterprise GDB is registered with OS authentication, but the ArcGIS Server service account is a local machine account that does not resolve the DB’s SPN/domain context. Edits fail. What is the misalignment?", "Align the service account model with OS-authenticated database access (domain service account, delegation, SPNs) per Esri and DBA requirements.", "Switch every connection to sa.", "Disable OS authentication.", "Publish only from Pro on desktops."),
        _row(d, "PII map layers require user attribution in audit logs. IWA is enabled on the Web Adaptor, yet public kiosk maps hit anonymous paths. Auditors see only anonymous access. What explains missing user identity?", "Anonymous or public app flows do not carry IWA user context; separate authenticated endpoints or app design is needed for per-user auditing.", "Enable anonymous IWA simultaneously for all URLs.", "Delete Web Adaptor logging.", "Turn off HTTPS for kiosk browsers."),
        _row(d, "A reverse proxy strips WebSocket upgrade headers. Portal home loads but hosted feature layer editing and some admin pages fail intermittently. What should be corrected?", "Proxy rules for WebSockets, long polling, timeouts, and Host forwarding per Esri reverse-proxy documentation.", "Disable editing in Portal org settings.", "Open port 6080 to the internet.", "Delete hosted layers."),
        _row(d, "Architects want vector tiles and editable features from the same authoritative data. What must be explicit in the design?", "Which workflows use hosting/relational store versus enterprise GDB services, tile generation cadence, and editing paths—not assuming one mechanism covers all.", "Vector tiles automatically replace feature services.", "Hosted layers cannot coexist with tiles.", "Disable editing for all vector layers."),
        _row(d, "A read-only warehouse GDB is registered; leadership now wants hosted editing against the same warehouse without a staging GDB. What tension should you surface?", "Hosted editing patterns, performance, and transactional behavior differ from direct enterprise publishing; plan schema, branching, and store roles deliberately.", "Enable editing without DBA review.", "Copy the warehouse to file geodatabase weekly.", "Merge warehouses into Portal content dir."),
        _row(d, "After a merger, the portal public URL changed. Field apps still embed the old hostname in saved web maps. DNS points to the new name. What still breaks OAuth clients?", "Client-stored URLs, OAuth redirect registrations, and organization links must be updated to the canonical portal name—DNS alone does not rewrite app data.", "Delete all items.", "Disable OAuth for mobile.", "Share primary admin password for scripts."),
        _row(d, "A synchronous flood model GP service times out under load while the portal UI stays responsive. Leadership blames Portal. What is the best isolation step?", "Measure GP service instances, tool I/O, and data paths; scale and tune the GP service—not assume Portal is the bottleneck.", "Add Portal machines only.", "Set GP to asynchronous without testing.", "Disable all hosted layers."),
        _row(d, "FIPS-only TLS is enforced; legacy rugged tablets cannot handshake with the Web Adaptor. What process should security and GIS follow?", "Test cipher suites against all required clients and negotiate a supported baseline—not maximum hardening without device inventory.", "Disable TLS on internal VLANs.", "Exempt GIS from all crypto policy.", "Use HTTP for tablets only."),
        _row(d, "Object store registration uses a public S3 endpoint, but the landing zone blocks public internet. Hosted attachments fail. What should change?", "Use private endpoints, VPC endpoints, or policy-allowed routes aligned with the object store registration—not a reachable-from-Server test from a browser alone.", "Disable attachments org-wide.", "Move attachments to email.", "Delete the object store without migration."),
        _row(d, "Dynamic ortho image services on high-latency NAS time out during pan/zoom. CPU is low. What is the first tuning axis before adding hardware?", "Caching, overviews/pyramids, mosaic performance, and storage IOPS—not only horizontal scaling of Portal.", "Delete pyramids to save space.", "Force synchronous drawing for all requests.", "Disable JPEG compression."),
        _row(d, "Notebook Server grants publisher broadly; notebook outputs reference sensitive UNC paths in logs. What control is missing?", "Least privilege on roles, output locations, and share ACLs for the Notebook run-as account—not publisher for all by default.", "Disable logging.", "Store outputs in Portal content only without review.", "Run notebooks as SYSTEM."),
        _row(d, "GeoEvent feed TLS was renewed; the feed shows connected but no rows insert. Password unchanged. What should you verify in the GeoEvent tier?", "Trust for the new server certificate in the GeoEvent/Java trust store and any client-auth settings—not only browser trust.", "Disable TLS on the feed.", "Reinstall Portal.", "Delete the spatiotemporal big data store blindly."),
        _row(d, "Two customer portals mistakenly federate one ArcGIS Server site. Publishing conflicts and ownership issues appear. What is the design fix?", "One portal should own a given Server site pattern; remove unsupported overlapping federation and realign architecture.", "Merge portals by copying directories.", "Share one primary admin across tenants.", "Disable one portal without unfederating."),
        _row(d, "A migration copied portal content directories expecting identical item IDs in a new portal. Web maps break. What principle was violated?", "Item IDs and URLs are portal-specific; use supported export/import or migration tooling—not raw folder copies for item identity.", "Re-use machine names only.", "Delete search index to fix IDs.", "Run two portals on one content dir."),
        _row(d, "SAML logins succeed, but portal roles from AD groups apply to some users and not others in the same group. What should you compare?", "Token group claims, nested group limits, attribute mapping, and what the IdP actually emits for each user—not only AD membership in LDAP.", "Delete custom roles.", "Disable nested groups in AD without IdP change.", "Assume SAML cannot carry groups."),
        _row(d, "Guest Wi-Fi uses captive DNS; Field Maps OAuth fails intermittently while corporate SSID works. What category is this?", "Client network path and DNS to OAuth endpoints; captive portals often block or redirect required hosts.", "A Field Maps bug on iOS only.", "Disable mobile OAuth globally.", "Require VPN for all field staff always."),
        _row(d, "Cloud raster store publishing works from Server node A but not node B in the same site. Same site config. What often differs?", "Per-node IAM/instance profile or credential resolution for the cloud store—not only shared config store.", "Reinstall node B with node A’s hostname.", "Disable multi-machine sites.", "Use only local file GDB."),
        _row(d, "Distributed collaboration is connected, but edits never arrive cross-org. Firewalls allow 443. What beyond connectivity matters?", "Sync direction, schedules, supported item types, and workspace membership—not only initial trust establishment.", "Collaboration is always synchronous.", "Delete and recreate AD users.", "Disable HTTPS on one portal."),
        _row(d, "A UNC data path resolves on an admin laptop drive mapping but not from all Server machines. Services start only on one node. What is the issue class?", "Consistent, service-account-visible paths (UNC with correct ACLs)—not user-specific mappings.", "Copy data to each desktop.", "Use subst drives on servers.", "Disable multi-machine clustering."),
        _row(d, "An HTTP-only widget requests tokens while the site is HTTPS-only; browsers block mixed content. Who must fix what?", "The app must call HTTPS endpoints and follow supported token patterns—mixed content cannot be ‘fixed’ by lowering portal security.", "Disable HTTPS for widgets.", "Set portal to HTTP internally and externally.", "Disable CORS globally."),
        _row(d, "SMTP allows internal relay only; external contractors never receive portal email invites. What is missing?", "A mail path that can deliver to external addresses per org policy—SMTP relay, allowed recipients, or alternative onboarding—not only portal SMTP ‘working’ for internal test.", "Disable email verification.", "Point portal SMTP at an open relay on the internet without authentication or allowlisting.", "Share admin passwords instead."),
        _row(d, "A browser widget uses localhost redirect URIs in production; users fail OAuth after promoting the app. What is wrong?", "Production redirect URIs must be registered for the real hostnames and environments—not dev localhost entries only.", "OAuth allows any redirect automatically.", "Disable OAuth for production.", "Use one client ID without URI list."),
        _row(d, "A second raster analytics Server site is federated; portal lists it, but hosted analytics outputs referencing it fail. What should you verify first?", "Reachability, data store registrations, and credentials for that federated site from the hosting tier—not only portal UI listing.", "Merge both config stores manually.", "Install Portal on the raster server.", "Disable HTTPS on the analytics site."),
        _row(d, "Authorization in Pro shows valid, but Pro claims licensing expired while Portal shows the user licensed. What should you reconcile?", "Named user types, add-ons, and which portal URL Pro signs into—align provisioning and sign-in target.", "Delete all named users.", "Remove Web Adaptor.", "Disable SAML only."),
        _row(d, "A base deployment will expose only 443 externally; internal components use 6443/7443. What pattern matches security guidance?", "Terminate TLS at Web Adaptor or reverse proxy; keep internal ports off the public internet unless architected explicitly.", "Publish 6443 on the public firewall.", "Bind Portal to HTTP only.", "Disable internal HTTPS."),
        _row(d, "Object store is configured yet large hosted attachments still fail. What is a likely gap?", "Object store health, limits, and registration versus expectations for blob size and throughput.", "Raster analytics is missing.", "Only tile cache size matters.", "Portal groups control attachment size."),
        _row(d, "An org enables anonymous access for a dashboard, but layers still prompt for login. What is the usual cause?", "Layer and item sharing must match the app audience across all dependencies—not only the app item.", "HTTPS is optional.", "Anonymous disables all layers automatically.", "Only the print service needs sharing."),
    ]

    # --- Troubleshoot (18) ---
    t = "troubleshoot-enterprise"
    rows += [
        _row(t, "Health scripts from a scheduler host report federated Server ‘Not reachable’ while your laptop browser opens the admin URL fine. What should you validate first?", "Network path, DNS, and allowed ports from the scheduler’s subnet to the Server admin URL—not only interactive admin tests.", "Reinstall Portal.", "Delete federation.", "Disable HTTPS for scripts."),
        _row(t, "After PostgreSQL maintenance, hosted layers fail; Pro connects to the same DB directly. Logs show auth failures from Server. What is a common miss?", "pg_hba / authentication rules and service account password alignment after maintenance—not only ‘DB is up’.", "Reinstall ArcGIS Server only.", "Delete hosted layers.", "Disable TLS on PostgreSQL."),
        _row(t, "Scene Viewer shows a flat globe on guest Wi-Fi; wired users see terrain. Other HTTPS sites work. What should you suspect?", "Guest network blocking or intercepting terrain/elevation endpoints or WebGL resources—not only the scene layer.", "Delete elevation globally.", "Disable WebGL for everyone.", "Reinstall Portal."),
        _row(t, "The print service cannot write to a temp path under a user profile on the server. Pro prints the same map. What is wrong?", "Server processes need machine-wide or service-account temp/output folders—not profile paths tied to an interactive login.", "Disable printing.", "Run Server as the interactive user forever.", "Delete all fonts."),
        _row(t, "One custom dashboard gets Invalid token after exactly one hour; other apps do not. What should developers audit?", "OAuth token lifetime and refresh handling in that app versus short-lived access tokens.", "Set portal token timeout to unlimited.", "Disable OAuth for that app only.", "Reinstall Web Adaptor."),
        _row(t, "SSL inspection re-signs external basemap TLS; basemaps randomly fail from Server. What should networking change?", "Exclude or properly trust inspected chains for Server outbound calls to known endpoints.", "Disable basemaps.", "Open all outbound ports without restriction.", "Disable TLS 1.2."),
        _row(t, "Portal search returns nothing after an index path change; disk was full and was freed. What restores search?", "Rebuild/reinitialize the search index per documentation after path or corruption issues—not only freeing disk.", "Delete all items.", "Disable search permanently.", "Copy another portal’s index files."),
        _row(t, "A web map is shared to a group, but layers owned by others are private to that group. Users see ‘cannot access item.’ What failed?", "End-to-end sharing of all dependent layer items—not only the web map item.", "Share web maps to Everyone only.", "Delete the layer owners.", "Disable group security."),
        _row(t, "IdP upgrade changes NameID format; automation and ownership links break. What must be coordinated?", "Portal identity mapping, script credentials, and IdP attribute policy for stable identifiers—not only ‘login works’.", "Delete enterprise logins.", "Rotate only Windows passwords.", "Merge all accounts manually without plan."),
        _row(t, "GP pegs CPU; increasing instances briefly helps. Data lives on a latent SMB share. What is the deeper issue?", "Data path latency and GP design—not only instance count.", "Set instances to unlimited.", "Move GP to Portal.", "Disable logging."),
        _row(t, "WMS GetMap works except from one subnet; others fine. First hypothesis?", "Network path, firewall, or proxy differences for that subnet to the service endpoint.", "Wrong spatial reference name only.", "Reinstall MapServer.", "Delete all layers."),
        _row(t, "Antivirus quarantined Server directory files during a scan; services fail until exclusions. What should be documented?", "AV exclusions for ArcGIS Server directories per vendor/Esri guidance and change-controlled scans.", "Disable AV on all servers without policy.", "Copy the config store to a removable drive nightly for ‘backup’ without stopping services.", "Run real-time scan on every REST call."),
        _row(t, "Fonts for labels work in Pro but not in a custom print service on Server. Fonts were installed only to the admin profile. Fix?", "Install fonts for all users or the ArcGIS Server account system-wide.", "Remove labels from all maps.", "Print as raster only always.", "Run print as Administrator interactively."),
        _row(t, "MDM-managed Android fails SSL handshake to Portal; iOS works. Custom enterprise CA is in play. What should be fixed on devices?", "Trust store for the portal chain and any inspection CA in the MDM profile—not only browser trust.", "Disable TLS on mobile.", "Use HTTP for Field Maps.", "Delete certificates on Portal."),
        _row(t, "Map image layer shows stale imagery after update; REST cache clear did not help; CDN still serves old tiles. What should you address?", "CDN/proxy cache TTLs, cache busting, or service cache update strategy—not only Server REST cache.", "Delete the service.", "Disable all caching forever.", "Rename the portal URL only."),
        _row(t, "502/504 at Web Adaptor during backups; Server CPU low. What interaction?", "Backup I/O locks or timeouts through the stack; coordinate maintenance windows and backup modes with service health.", "The Web Adaptor host is idle; 502/504 must be a false alarm from load balancer health probes only.", "Disable backups without policy.", "Set all instances to zero."),
        _row(t, "HTTP/2 on a reverse proxy breaks some Portal admin operations; HTTP/1.1 sites work. What should you review?", "Proxy HTTP/2 compatibility, timeouts, and Esri-documented rules for Portal admin traffic.", "Disable Portal admin API.", "Downgrade Portal to HTTP.", "Delete Web Adaptor."),
        _row(t, "Intermittent ‘Invalid token’ across apps after SSL inspection rollout. What direction?", "Trust and inspection policy for OAuth/token endpoints—pinned roots or exclusions per security policy.", "Disable OAuth org-wide.", "Open all ports.", "Set tokens to never expire."),
    ]

    # --- Maintain (22) ---
    m = "maintain-support-enterprise"
    rows += [
        _row(m, "WebGISDR full export never finishes in the allotted window; leadership refuses more storage. What must change?", "RTO/RPO feasibility: scope, staging capacity, or backup architecture—not pretending the window will shrink without design change.", "Skip relational exports.", "Run during peak hours to finish faster.", "Delete logs only."),
        _row(m, "Cold-site restore brings Portal up; collaboration trusts fail though versions match. What did the drill omit?", "Full trust re-establishment, DNS, and URL plans in the DR context—not only starting services.", "Reinstall Windows on all nodes.", "Copy content dirs without DB restore.", "Ignore hostname guidance."),
        _row(m, "Relational log volume exploded after ‘temporary’ verbose DB logging. Disk critical. Sequence?", "Return to supported log levels, archive/rotate, free space—then targeted troubleshooting.", "Delete .mdf files manually.", "Disable relational store.", "Format the log drive live."),
        _row(m, "Immutable backup requirement unmet: backups live on writable domain shares. Ransomware tabletop fails. What architecture helps?", "Immutable/WORM/offline media or cloud object-lock with separate credentials—not domain-shared RW alone.", "Snapshots are always sufficient.", "Tape cannot fail.", "Delete old backups to save space without policy."),
        _row(m, "Yearly tape restore test fails media read. Leadership funds only tape. Honest risk statement?", "Verify restores and media lifecycle; single media type without testing is a known gap.", "Tape is always reliable.", "Cloud is immutable without settings.", "RTO equals backup duration."),
        _row(m, "OS patches reset ACLs on Server directories; services stop until fixed. What reduces surprise?", "Change control noting GPO/security tools and documented ACL restoration for the ArcGIS Server account.", "Run services as Domain Admin.", "Disable patches.", "Delete config store when permissions break."),
        _row(m, "Portal patched without Server; federated publishing breaks. What should upgrades follow?", "Supported version matrices and documented patch order across Enterprise components.", "Patch random components independently.", "Assume Server auto-patches with Portal.", "Skip release notes."),
        _row(m, "Weekly index rebuilds ‘for performance’ cause search flaps. What is wrong?", "Index maintenance when evidence supports it—not blanket churn without monitoring.", "Rebuild every hour.", "Delete index files while running.", "Disable search to stabilize."),
        _row(m, "DB maintenance runs during GIS peak because it fits the DBA timezone. Editors timeout. What should happen?", "Coordinate heavy DB work with GIS maintenance windows or stagger load.", "Run DBCC only at GIS peak.", "Disable GIS during DB work without notice.", "Never coordinate teams."),
        _row(m, "Snapshot backups cause brief I/O pauses nightly; leadership denies user impact. What should be measured?", "Service latency and error rates during backup windows with correlation to snapshots.", "Disable monitoring during backups.", "Snapshots have zero I/O cost always.", "Delete snapshots to fix latency."),
        _row(m, "DR restore of DBs without tile cache volumes leaves hosted scenes incomplete at fine scales. What was incomplete?", "Coordinated restore of relational, content, and cache tiers per recovery objectives—not independent ‘latest’ pieces.", "Cache is optional always.", "Restore only Portal VM.", "Skip file backups."),
        _row(m, "Search index and content backups on different schedules; restore yields searchable gaps. What should align?", "Recovery point consistency across components or documented reconciliation—not mismatched timestamps blindly.", "Always restore newest file from each tier without plan.", "Delete search to fix mismatches.", "Disable incremental backups."),
        _row(m, "Personal data appears in portal logs because verbose logging captured query parameters. Remediation?", "Redact/disable sensitive fields, rotate logs, and enforce retention—not logging everything indefinitely.", "Publish logs publicly.", "Disable HTTPS logging only.", "Ignore compliance."),
        _row(m, "Moving index storage to a new volume still writes to the old path. What was missed?", "Complete portal configuration change for index location and service restart per documentation—not only copying files.", "Delete index files manually.", "Disable search.", "Reboot clients only."),
        _row(m, "Backup vendor renewal doubles cost; leadership deletes old backups to pay invoice. What must precede deletion?", "Retention/compliance requirements and risk acceptance—not ad hoc cost cutting.", "Backups are infinite by default.", "Ransomware never touches backups.", "Tape is always online."),
        _row(m, "Memory alerts on Data Store ignored for quarters; OOM kills the store during peak. What failed?", "Capacity planning and acting on sustained growth trends—not silencing alerts.", "Restart weekly forever.", "Disable monitoring.", "Add RAM without measuring workload."),
        _row(m, "Zero-downtime upgrade demanded on a single-machine deployment. What must be clarified?", "Architectural limits; true zero downtime needs HA design—not a policy label on one server.", "Snapshots guarantee zero downtime.", "Maintenance mode removes all risk.", "Upgrade without backup."),
        _row(m, "Cold standby hardware fails annual power-on due to expired firmware licenses. DR test lesson?", "DR includes powering and validating standby stacks, firmware, and dependencies—not only software restore.", "Cold standby never powers on in tests.", "Firmware is irrelevant.", "DR is only a spreadsheet."),
        _row(m, "TLS disabled for DB ‘to speed queries’; Esri clients fail. What process was skipped?", "Compatibility validation across ArcGIS and DB TLS settings before production change.", "Apply crypto changes Friday 5pm without staging.", "Disable TLS everywhere.", "Use HTTP to the database."),
        _row(m, "WebGISDR run during business hours causes user-visible outages. Mistake?", "Run disruptive exports in maintenance windows or staged environments—not peak load.", "WebGISDR never touches I/O.", "Always run at peak for speed.", "DR exports only backup PDFs."),
        _row(m, "Relational HA ‘added a machine’ without following Esri relational HA patterns. Misconception?", "Supported HA requires documented topology and versions—not simply an extra VM.", "Two primaries are always valid.", "Standby needs no network to primary.", "Relational store replaces backups."),
        _row(m, "Clearing REST cache after every small map change causes performance flapping. Better practice?", "Clear when service definitions change materially; excessive clearing removes beneficial caches.", "Never clear cache.", "Clear every minute.", "Disable cache at reverse proxy always."),
    ]

    # --- Manage (26) ---
    g = "manage-content-users"
    rows += [
        _row(g, "Org policy blocks sharing to Everyone; a team publishes a ‘public’ dashboard via a widely named internal group. What is the governance tension?", "Public visibility must follow approved mechanisms and policy; naming groups ‘public’ does not bypass org rules.", "Group name makes content world-visible.", "Disable HTTPS for internal maps.", "Use primary admin for all public items."),
        _row(g, "SAML users remain listed in Portal for days after IdP disablement. What should expectations reference?", "Periodic group/membership sync and connector behavior—not always instantaneous removal.", "AD changes are always instant in Portal.", "Portal ignores IdP after first login.", "Delete portal nightly."),
        _row(g, "Two automation apps share one OAuth client secret in a wiki; one team rotates it silently. What practice fixes this?", "Separate confidential clients, secure secret storage, and rotation procedures—not shared long-lived secrets.", "One secret for all jobs forever.", "Commit secrets to Git for backup.", "Use primary admin password in jobs."),
        _row(g, "LDAP filters include service accounts that should not consume licenses. What should be tightened?", "Filter criteria and license assignment rules so only intended humans receive seats—not broad LDAP queries.", "Give everyone Publisher for simplicity.", "Disable LDAP sync.", "Assign licenses by first name."),
        _row(g, "Group owner on leave without delegate; shared update group cannot be administered. Preventive policy?", "Deputy owners or admin transfer workflows for critical groups before extended absence.", "Groups auto-reassign randomly.", "Delete inactive owners without notice.", "Use shared accounts for ownership."),
        _row(g, "Collaboration workspace allows features but attachments do not sync; settings allowed features only. Outcome?", "Supported content types and sync rules determine what moves—not only ‘connected’.", "Collaboration always syncs everything.", "Attachments are impossible in Enterprise.", "Delete collaboration."),
        _row(g, "Custom role publishes hosted layers but cannot share to the org; items stay invisible. Role bug?", "Publishing and sharing are distinct privileges; users may need sharing rights or group workflows.", "Publishing implies org visibility always.", "Delete custom roles.", "Share only via email."),
        _row(g, "Pop-ups hide attributes, but WMS GetFeatureInfo still exposes them. What was misunderstood?", "OGC/REST capabilities are independent of pop-up UX; control sensitivity at the service and data model.", "Pop-ups are the security boundary.", "WMS cannot return attributes.", "Disable REST to fix WMS."),
        _row(g, "Delete protection is on for an item, but the service is removed in Server Manager. What integrity issue remains?", "Orphaned portal items referencing missing services; clean up items and dependencies deliberately.", "Portal prevents all deletes always.", "Server Manager syncs item state automatically.", "Delete protection blocks Server deletes."),
        _row(g, "Collaboration invitations fail because guest accounts are disabled in one org. Conflict?", "Cross-org collaboration may require guest or partner identity policies to align—not only technical connectivity.", "Disable collaboration for all.", "Merge AD forests casually.", "Use anonymous partner access for edits."),
        _row(g, "Multiple portals federate one Server site accidentally. Correct ownership?", "One portal should own a site; unfederate extras per supported procedures and redesign.", "Federation merges orgs.", "Second portal is read-only automatically.", "Use one Server per user."),
        _row(g, "External members are allowed in a group containing layers policy forbids from outside. What must be reviewed?", "Data sensitivity, group membership rules, and sharing—not only the web map item.", "Groups override classification automatically.", "External members cannot see layers ever.", "Disable HTTPS for partners."),
        _row(g, "Premium routing enabled org-wide; notebooks burn credits. Control?", "Least privilege on premium capabilities and monitoring—not everyone needs routing.", "Credits are untraceable in Enterprise.", "Routing is free in Portal.", "Delete analytics without communication."),
        _row(g, "Built-in and SAML accounts collide after cutover; ownership is messy. What should have been planned?", "Identity migration, duplicate handling, and attribute mapping before switching auth models.", "SAML merges accounts automatically.", "Delete all content pre-cutover.", "Use identical passwords."),
        _row(g, "Nightly AD group sync means morning role changes wait until overnight. What expectation should be set?", "Sync latency and manual override processes—not instant role change guarantees in all configurations.", "Sync runs every second always.", "Disable sync and use CSV only.", "Delete AD groups weekly."),
        _row(g, "Viewer role users export data because the service allows query/export. Leadership blames Portal. Where is control?", "Service capabilities and layer settings—not portal viewer labels alone.", "Viewer blocks all exports always.", "Portal overrides service flags.", "Disable Pro exports globally."),
        _row(g, "Web map schema lags after Pro schema edit to a hosted layer. Common cause?", "Refresh/republish layer item metadata or client cache; verify the updated layer is what the web map references.", "Portal forbids schema change.", "Delete the web map silently.", "Wait indefinitely without checking."),
        _row(g, "Distributed collaboration retention policies differ; deletes do not propagate. Possible reason?", "Legal/policy constraints may forbid destructive sync; settings reflect governance—not technical failure.", "Collaboration always mirrors deletes.", "Retention is cosmetic.", "Delete legal review."),
        _row(g, "Long-lived cloud keys for data store registration sit in a shared folder in plain text. Audit finding. Replacement?", "Secrets in vault/rotation patterns and least-privilege keys—not shared drives.", "Keys in README are fine if repo is private.", "Rotate keys yearly without automation.", "Use primary admin keys for data."),
        _row(g, "Org basemap gallery defaults to global endpoints; regulations require national basemaps. Who sets the default experience?", "Organization featured content and basemap gallery settings—not each user’s Pro project alone.", "Groups set per-user basemaps always.", "National basemap endpoints are controlled by the coordinate system of the default enterprise geodatabase.", "Disable Living Atlas without review."),
        _row(g, "Tokens embedded in a public GitHub demo repo can access org resources. Exposure?", "Revoke tokens, rotate secrets, and use proper OAuth confidential/public patterns—never commit tokens.", "HTTPS repos hide tokens.", "GitHub auto-redacts portal tokens.", "Anonymous users cannot use tokens."),
        _row(g, "A web map mixes emergency and routine layers; partner collaboration workspaces intended separation. What failed?", "Item grouping and sharing must match information governance—not only technical collaboration setup.", "Collaboration enforces labels automatically.", "Web maps cannot mix layers.", "Delete partner org."),
        _row(g, "Credits spike from one project using GeoAnalytics org-wide. Cost control?", "Role-based tool access and usage monitoring—not enabling premium tools for all publishers.", "Enterprise credits are unlimited.", "Portal cannot show usage.", "Assign GeoAnalytics to all viewers."),
        _row(g, "WFS exposes full schema while the app UI looks read-only. Risk?", "Protocol exposure is independent of UI; lock OGC/REST capabilities to match sensitivity.", "WFS is always attribute-free visually.", "OGC ignores security labels.", "Disable REST only."),
        _row(g, "Same email maps to built-in and SAML identities; ownership splits. Prevention?", "Identity strategy and deduplication before enterprise login cutover—not only enabling SAML.", "Portal merges duplicates nightly automatically.", "Delete SAML users weekly.", "Share one password."),
        _row(g, "Org-wide ‘Everyone’ sharing disabled; manager demands a public dashboard tomorrow. Best answer?", "Use approved public mechanisms and policy exceptions—not bypassing security with shared credentials.", "Use primary admin for public items.", "Disable org security temporarily.", "Publish to anonymous SMB."),
    ]

    assert len(rows) == 100, len(rows)
    return rows


if __name__ == "__main__":
    from collections import Counter

    c = Counter(x[0] for x in get_extra_100_case_study_scenarios())
    print(c)
    print("total", sum(c.values()))
