#!/usr/bin/env python3
"""
100 scenarios: portal usage vs Monitor, DMZ/firewall ports, maintenance windows,
Server Manager vs Portal admin, groups/roles/sharing, WebGISDR, tokens, LDAP,
WebContextURL, ArcGIS Server account — EIG-weighted segment (34/18/22/26 %).

Returns tuples: (domainId, stem, correct, wrong1, wrong2, wrong3).

Distractor policy: eaep_distractor_design.py (on-domain wrong answers; plausible misconfigurations).
"""

from collections import Counter


def _q(domain, stem, c, w1, w2, w3):
    return (domain, stem, c, w1, w2, w3)


def get_extra_100_ops_scenarios():
    rows = []
    d, t, m, g = (
        "deploy-enterprise",
        "troubleshoot-enterprise",
        "maintain-support-enterprise",
        "manage-content-users",
    )

    # --- deploy-enterprise (34) — ports, WebContext, deployment boundaries ---
    rows += [
        _q(
            d,
            "An analyst needs to understand **which groups and roles** are associated with **maps, apps, and layers**, and how heavily those items are used. Which combination best matches typical Esri guidance?",
            "Use **Portal** item and member usage views/reports for app/map/layer usage tied to sharing and roles; use **ArcGIS Monitor** for infrastructure and service health metrics—not a substitute for portal usage analytics.",
            "Use only ArcGIS Monitor for item-level usage and role-to-content mapping.",
            "Use only Server Manager logs for portal group membership.",
            "Use Active Directory Users and Computers for map usage counts.",
        ),
        _q(
            d,
            "A workstation in a **DMZ** must reach an **internal** ArcGIS Enterprise deployment that is published through a **Web Adaptor** on 443. Internal Portal and Server use 7443/6443 inside the trusted network. What should the firewall between DMZ and internal typically allow for **standard end-user HTTPS access** (not raw admin URLs)?",
            "**443** to the Web Adaptor (or reverse proxy) entry that fronts Portal/Server; **do not** expose internal 6443/6443/7443 to the DMZ for general users unless architected explicitly—clients use the public 443 endpoint.",
            "Open 6443 and 7443 from DMZ directly to every internal GIS server for all users.",
            "Open 80 and 443 to Portal machine bypassing the Web Adaptor for security.",
            "Require DMZ clients to use 6443 + 7443 only with no 443.",
        ),
        _q(
            d,
            "Security asks which ports must be reachable **from the internet** to a **single public-facing Web Adaptor** that fronts Portal and federated Server. Best-practice answer?",
            "**HTTPS 443** (and optionally HTTP 80 only if redirecting to HTTPS) on the Web Adaptor host or load balancer—not direct exposure of ArcGIS Server 6443 or Portal 7443 to the public internet in a typical design.",
            "Expose 6443 and 7443 publicly so clients can bypass the Web Adaptor.",
            "Expose 6080 publicly for REST convenience.",
            "Open all ports 1–65535 on the Web Adaptor host.",
        ),
        _q(
            d,
            "An admin’s laptop on the **corporate LAN** uses **Server Manager** and **Portal Administrator** URLs. Which ports are commonly involved **internally** (defaults) when not using a Web Adaptor for admin URLs?",
            "**6443** for ArcGIS Server Administrator Directory / Server Manager patterns and **7443** for Portal Administrator over HTTPS on the respective machines—subject to your URLs and WA configuration.",
            "Port 443 is sufficient for all admin access since Web Adaptor proxies all Server Manager traffic.",
            "6443 and 7443 are only relevant when Server Manager runs on the database machine.",
            "6080 is required for every Portal admin action.",
        ),
        _q(
            d,
            "You set **WebContextURL** / organization URL so external clients use `https://maps.org.com/portal`. Internal staff still browse by machine name. What problem does WebContextURL primarily solve?",
            "Consistent **public hostname and HTTPS** in generated links, OAuth redirects, and client configurations—not only cosmetic branding.",
            "WebContextURL replaces the need for Web Adaptor.",
            "WebContextURL disables internal access.",
            "WebContextURL is only for email SMTP.",
        ),
        _q(
            d,
            "**privatePortalURL** (or internal URL) vs public WebContextURL: why both may exist?",
            "Support **split DNS / internal vs external** access paths so components and some clients resolve the correct endpoint while public OAuth uses the canonical URL.",
            "They must always be identical byte-for-byte.",
            "privatePortalURL is deprecated and unused.",
            "Both URLs must always match; using different hostnames triggers OAuth redirect mismatches.",
        ),
        _q(
            d,
            "Federation validation references **Server URL** and **Services URL**. A mistake admins make?",
            "Using machine-only or internal URLs for **Services URL** that clients cannot resolve—align public service URLs with DNS and Web Adaptor names users actually use.",
            "Services URL must always use port 6080.",
            "Server URL and Services URL must differ by definition.",
            "Federation ignores Services URL.",
        ),
        _q(
            d,
            "The **ArcGIS Server site** runs under the **ArcGIS Server account**. What is it primarily used for?",
            "OS-level access to **config store, directories, registered data**, and resources the services need—not an interactive user login for daily GIS work.",
            "The same as the Portal primary administrator login for all tasks.",
            "A domain account that replaces database sa everywhere.",
            "An anonymous IIS identity only.",
        ),
        _q(
            d,
            "Changing the **ArcGIS Server account** password without updating **data store** and **file** registrations. Expected outcome?",
            "Services may fail to access data until credentials and SPNs are updated consistently—follow Esri procedures for account changes.",
            "Password changes propagate automatically to all databases.",
            "Portal data store registrations inherit the Server service account password automatically.",
            "Server account password does not affect registered folders.",
        ),
        _q(
            d,
            "**Primary site administrator** in Server Manager vs **Portal** built-in administrator: key distinction?",
            "Server’s primary admin governs the **ArcGIS Server site**; Portal has its own admin model—do not conflate passwords and roles across products.",
            "They are always the same account by design.",
            "Primary site administrator replaces Portal admin.",
            "Disable one when using SAML.",
        ),
        _q(
            d,
            "LDAP identity store in Portal: what does it primarily enable?",
            "Importing and syncing **enterprise users and groups** from LDAP into Portal membership—not replacing SAML login by itself unless configured that way.",
            "LDAP removes the need for Web Adaptor.",
            "LDAP is only for tile caches.",
            "LDAP sync replaces relational data store.",
        ),
        _q(
            d,
            "**LDAP** group filters that are too broad. Risk?",
            "Unintended users receive **roles or licenses** tied to those groups—tighten filters and portal group mapping.",
            "LDAP filters cannot affect licensing.",
            "Broad filters improve security automatically.",
            "LDAP ignores group nesting always.",
        ),
        _q(
            d,
            "A custom app requests a **long-lived token**. Portal issues **short-lived access tokens**. Best practice?",
            "Use **OAuth refresh tokens** or app-appropriate flows per Esri security guidance—not embedding primary admin tokens.",
            "Set portal token timeout to unlimited for all apps.",
            "Share one service account password in the app config.",
            "Disable OAuth for internal apps.",
        ),
        _q(
            d,
            "**Shared token** patterns in custom integrations: pitfall?",
            "Tokens are **secrets**; rotating Portal or OAuth secrets requires updating all integrations—avoid hard-coding in public repos.",
            "Shared tokens never expire.",
            "HTTPS prevents token theft without any other controls.",
            "Portal tokens are safe in query strings on public sites.",
        ),
        _q(
            d,
            "Reverse proxy listens on **443**; Portal listens on **7443** internally. Client browsers must not see mixed HTTP/HTTPS to Portal hosts. Correct pattern?",
            "Terminate TLS at proxy/Web Adaptor; use HTTPS end-to-end per design—not HTTP between proxy and Portal in production without a deliberate exception.",
            "HTTP between proxy and Portal is always fine internally.",
            "Disable HTTPS on Portal to simplify.",
            "Use port 80 only for all internal hops.",
        ),
        _q(
            d,
            "**Kerberos** (IWA) port expectations on Windows: typical?",
            "Kerberos uses standard AD ports (e.g., **88** for KDC) and correct DNS/SRV—not ‘open 6443 for Kerberos’ as a substitute for design.",
            "Kerberos requires only port 443 on the GIS server.",
            "IWA never uses DNS.",
            "Disable port 88 for security.",
        ),
        _q(
            d,
            "Between **two GIS tiers** (Portal machine and Server machine), firewall: what is commonly required for federation?",
            "Bidirectional **HTTPS** connectivity on the ports your URLs use (often **6443** and **7443** defaults) plus stable DNS—not only outbound from Portal.",
            "Only outbound HTTPS from Portal to the Server admin URL is needed; Server never initiates callbacks.",
            "Federation uses only port 22.",
            "Disable all firewall rules after federation succeeds once.",
        ),
        _q(
            d,
            "**Database** listens on 1433 / 5432 on a separate DB host. Who needs access?",
            "The **relational data store** and/or service accounts that connect—not every end-user workstation.",
            "Open database ports to the internet for convenience.",
            "Portal users connect directly to 1433 for maps.",
            "Web Adaptor proxies all database traffic on 443.",
        ),
        _q(
            d,
            "**ArcGIS Monitor** agent communication: conceptual difference from portal usage reports?",
            "Monitor collects **operations metrics** from registered components; **portal usage** reports item/member activity—different questions, both useful.",
            "Monitor replaces portal usage reports completely.",
            "Usage reports replace Monitor completely.",
            "Neither requires network connectivity.",
        ),
        _q(
            d,
            "You need **service-level CPU** and **memory** for federated servers. First stop?",
            "**ArcGIS Monitor** or Server logs/metrics—not the portal item usage page.",
            "Portal organization reports show Server CPU per service.",
            "ArcGIS Monitor only exposes portal user-count metrics, not per-service Server resource usage.",
            "Relational data store shows Server CPU.",
        ),
        _q(
            d,
            "**Web Adaptor** installation account vs **ArcGIS Server account**: confusion to avoid?",
            "They serve different roles—WA install/service identity vs Server site run-as account; do not merge without understanding ACL impacts.",
            "They must always be the same Windows account.",
            "Web Adaptor replaces Server account.",
            "Server account installs Web Adaptor always.",
        ),
        _q(
            d,
            "**Portal** **7443** vs **7080** (HTTP) in lab: production guidance?",
            "Use **HTTPS** and supported TLS for production; HTTP-only is not a production security pattern for Portal.",
            "7080 is required for OAuth in production.",
            "Disable 7443 and use 7080 only.",
            "Portal never uses HTTPS.",
        ),
        _q(
            d,
            "**Multi-machine Server**: port **4004** (and related) for inter-node communication. Admin takeaway?",
            "Allow **site communication** ports between cluster nodes per Esri documentation—not only client-to-server 443.",
            "4004 is only for email.",
            "Multi-machine sites need no internal ports.",
            "Open 4004 to the public internet.",
        ),
        _q(
            d,
            "**Email (SMTP)** for Portal notifications: which component configures it?",
            "**Portal** organization email settings—not ArcGIS Server Manager alone.",
            "Server Manager SMTP replaces Portal email.",
            "ArcGIS Server Manager SMTP settings also control Portal email notifications in federated deployments.",
            "Web Adaptor hosts SMTP.",
        ),
        _q(
            d,
            "**ArcGIS Enterprise Builder** context: when is **443** on the built machine relevant?",
            "As part of the **Web Adaptor** or IIS binding for the chosen deployment pattern—not magic automatic public DNS.",
            "Builder opens 443 on every router automatically.",
            "Builder never uses 443.",
            "443 is only for PostgreSQL.",
        ),
        _q(
            d,
            "Client in **guest Wi-Fi** cannot reach `https://org.maps.com:7443`. Expected?",
            "Users should use the **Web Adaptor URL on 443**, not raw Portal **7443**—guest networks often block nonstandard ports.",
            "Open 7443 on every guest firewall by default.",
            "Portal requires 7443 on clients always.",
            "Disable Web Adaptor for guest users.",
        ),
        _q(
            d,
            "**OAuth** **redirect URI** registration includes `https://app:7443/...`. Mobile fails. Likely?",
            "Mobile apps must use **reachable URIs** on **443** through WA or approved schemes—not embedded 7443 to internal Portal.",
            "7443 is required on all mobile devices.",
            "OAuth ignores redirect URIs.",
            "Disable mobile OAuth.",
        ),
        _q(
            d,
            "**SSL certificate** on Web Adaptor vs internal Portal cert. Common deployment?",
            "Public CA on **client-facing** endpoint; internal trust chains for **server-to-server** communication validated separately.",
            "One self-signed cert works for every tier without trust issues.",
            "Internal Portal never needs TLS.",
            "Certificates are only for email.",
        ),
        _q(
            d,
            "**Z**scaler or **proxy** intercepts HTTPS to Portal. Enterprise logins fail. Direction?",
            "Configure **trust or exclusions** for Portal/OAuth per policy—not disable all TLS inspection blindly without security review.",
            "Disable SAML when using proxies.",
            "Portal cannot work with proxies.",
            "Use HTTP through the proxy only.",
        ),
        _q(
            d,
            "**Port 6080** (HTTP) to ArcGIS Server: when is it relevant?",
            "Often **disabled or blocked** in hardening; **HTTPS 6443** is standard—6080 is not the primary production pattern for external access.",
            "6080 must be open to the internet for REST.",
            "6080 replaces 6443 always.",
            "All clients should use 6080 for speed.",
        ),
        _q(
            d,
            "**Load balancer** health check on 443 returns 200 but OAuth fails. Lesson?",
            "Health checks may not validate **OAuth endpoints** or **session affinity** needs—deepen monitoring.",
            "443 success means OAuth always works.",
            "OAuth uses port 6080 only.",
            "Remove load balancer for Portal.",
        ),
        _q(
            d,
            "**IPv6** only clients to **IPv4** only Portal behind WA. Issue?",
            "Network path and dual-stack or proxy design—not something Portal ‘fixes’ alone.",
            "Portal auto-translates IPv6 to IPv4 always.",
            "Disable IPv4 on Portal.",
            "Web Adaptor requires IPv6 only.",
        ),
        _q(
            d,
            "**SDE connection** from Server to DB: firewall between Server and DB tier?",
            "Allow the **database port** from the **Server machine(s)** to the DB host—not from end users.",
            "Every client opens the database port.",
            "Portal opens DB port for all browsers.",
            "Firewall cannot affect SDE.",
        ),
        _q(
            d,
            "**Collaboration** HTTPS between two Portals: typical?",
            "**443** between orgs’ published endpoints; validate trust and any **pinning** requirements—not arbitrary 7443 peering.",
            "Collaboration requires raw 7443 between data centers always.",
            "Collaboration uses only SMTP.",
            "Disable HTTPS for collaboration.",
        ),
    ]

    # --- troubleshoot-enterprise (18) ---
    rows += [
        _q(
            t,
            "Portal **usage** shows zero views for a popular app while **Monitor** shows heavy map service traffic. First interpretation?",
            "**Usage** may not count certain client paths or caching; **Monitor** reflects service hits—reconcile definitions and CDN/proxy effects before blaming ‘wrong numbers’.",
            "Portal usage is always authoritative for every request.",
            "Monitor always duplicates portal view counts.",
            "Delete Monitor agents.",
        ),
        _q(
            t,
            "After a **maintenance window**, **Server Manager** opens but hosted layers fail. Portal admin UI works. Where to look first?",
            "**Hosting server** and **relational/tile** data store health after changes—not only Portal status.",
            "If Server Manager is accessible, all ArcGIS Server services are healthy; only Portal logs need review.",
            "Reinstall Web Adaptor first.",
            "Delete all hosted layers.",
        ),
        _q(
            t,
            "**DMZ** scanner reports **open 6443** to internal Server. Risk?",
            "Unnecessary **attack surface**—prefer WA on **443** and restrict direct Server ports to trusted networks per design.",
            "6443 must be public for REST.",
            "Open 6443 improves performance always.",
            "DMZ scanners are always wrong.",
        ),
        _q(
            t,
            "**WebContextURL** changed; **shared token** apps still call old hostname. Symptom?",
            "**Invalid token** or wrong endpoint—update app configs and OAuth redirects to the new canonical URL.",
            "WebContextURL changes are instant for all apps without updates.",
            "Tokens ignore hostname.",
            "Disable HTTPS to fix tokens.",
        ),
        _q(
            t,
            "**LDAP** sync shows users but **login** fails with SAML. Check?",
            "**SAML IdP** configuration and attribute mapping—not LDAP sync alone.",
            "LDAP replaces SAML.",
            "Delete LDAP when using SAML.",
            "SAML only works without LDAP.",
        ),
        _q(
            t,
            "**Administrative group** members cannot access **Server Manager** though they are Portal admins. Why?",
            "**Server** privileges are separate from Portal roles—assign **ArcGIS Server** privileges or use the right Server admin URL/account.",
            "Portal admin always implies Server primary admin.",
            "Server Manager uses Portal token only.",
            "Disable Server security.",
        ),
        _q(
            t,
            "**Portal group owner** deleted; **shared update** group locked. Recovery?",
            "**Portal** admin recovery or **transfer ownership** workflows—not Server Manager.",
            "Server Manager changes group owners.",
            "AD deletion auto-transfers portal groups.",
            "Delete the group without backup.",
        ),
        _q(
            t,
            "**WebGISDR** export fails with disk full mid-run. Partial files on share. Next?",
            "Free space, validate **staging** sizing, and rerun a **consistent** export per guidance—not assume partial is restorable.",
            "Partial WebGISDR is always valid.",
            "Delete relational store to continue.",
            "Skip tile cache in export always.",
        ),
        _q(
            t,
            "**Restore** from WebGISDR: Portal starts; **federated Server** shows **Not reachable**. Common miss?",
            "**Trust/certs/DNS** between Portal and Server admin URL in restore environment—not only ‘Portal is up’.",
            "Federation never survives restore.",
            "Reinstall Server without checking URLs.",
            "Disable HTTPS on Server.",
        ),
        _q(
            t,
            "**Usage report** shows spikes; **Monitor** shows CPU flat. Conclusion?",
            "Traffic may be **cached** or **edge-served**; correlate both with service logs.",
            "Flat CPU means users lie about usage.",
            "Delete usage reporting.",
            "Monitor is broken if CPU flat.",
        ),
        _q(
            t,
            "**Token** works in browser; **curl** to same URL fails with 401. Cause class?",
            "**IWA** or **browser-only** auth paths—scripts need token/OAuth.",
            "curl cannot use HTTPS.",
            "Portal blocks curl always.",
            "Disable token authentication.",
        ),
        _q(
            t,
            "**Primary Server account** password rotated; **registered folders** fail. Fix?",
            "Update **folder** credentials and service account **ACLs** per Esri steps.",
            "Folders ignore Server account.",
            "Registered folder credentials are managed separately from the Portal service account password.",
            "Delete registered folders.",
        ),
        _q(
            t,
            "**7443** reachable internally; external users on **443** see SSL errors. Issue?",
            "**Certificate/SAN** mismatch on **client-facing** endpoint—not internal 7443 cert.",
            "Users must use 7443 externally.",
            "Install cert only on database.",
            "Disable SAN on certificates.",
        ),
        _q(
            t,
            "**LDAP** **secure** (636) vs **389**: troubleshooting?",
            "Match Portal LDAP settings to what your directory actually exposes and requires for TLS.",
            "389 is always encrypted.",
            "636 never needs certificates.",
            "LDAP port does not matter.",
        ),
        _q(
            t,
            "**Sharing** set to org; **usage** still shows zero for external partners. Why?",
            "Partners are **not** in the org—usage is scoped; use **collaboration** or appropriate sharing for cross-org analytics visibility.",
            "Usage always includes anonymous internet.",
            "Sharing ignores membership.",
            "Delete external partners.",
        ),
        _q(
            t,
            "**Maintenance window** banner ignored; users edit during upgrade. Symptom?",
            "**Concurrent edit** failures or partial outages—communicate and enforce read-only if required.",
            "Banner blocks edits automatically.",
            "Maintenance mode stops databases always.",
            "Users cannot log in during any banner.",
        ),
        _q(
            t,
            "**ArcGIS Monitor** alert: Server down; Portal still serves cached **basemap**. Misunderstanding?",
            "**Cached tiles** may still draw while dynamic layers fail—validate which services are actually down.",
            "If basemap draws, Server cannot be down.",
            "Monitor alerts are always false.",
            "Basemap proves Portal is healthy.",
        ),
        _q(
            t,
            "**WebContextURL** and **privatePortalURL** both set; some **ArcGIS Pro** users get wrong **sharing** links. Check?",
            "**Pro** sign-in URL and **portal URL** alignment—not only browser bookmarks.",
            "Pro ignores WebContextURL.",
            "Sharing links always use machine name.",
            "Uninstall Pro to fix links.",
        ),
    ]

    # --- maintain-support-enterprise (22) ---
    rows += [
        _q(
            m,
            "You schedule a **Portal maintenance window** in organization settings. What is it **not**?",
            "A guarantee that **all** background jobs stop or that **databases** enter maintenance mode automatically—it is primarily **communication** to users.",
            "A technical lock that prevents all logins automatically in all releases.",
            "A replacement for WebGISDR.",
            "A setting that patches Portal without admin action.",
        ),
        _q(
            m,
            "**WebGISDR** **full** export cadence vs **incremental** expectations: admin truth?",
            "Understand what each mode backs up and your **RPO/RTO**—not ‘incremental’ equals all use cases.",
            "Incremental WebGISDR always includes every database byte.",
            "Full export is never needed after first run.",
            "WebGISDR replaces VM snapshots entirely always.",
        ),
        _q(
            m,
            "**WebGISDR** to a **cloud** bucket: prerequisite?",
            "Stable **network**, **permissions**, and **space** for the export payload—validate restore **from** cloud to on-prem if that is your DR story.",
            "Cloud bucket makes restore automatic without testing.",
            "WebGISDR only writes to C:.",
            "Disable encryption for cloud speed.",
        ),
        _q(
            m,
            "**Restore** drill: run **WebGISDR** **import** to an isolated VLAN. Success criteria?",
            "End-to-end **login**, **federation**, **hosted layers**, and **data** paths—not only HTTP 200 on Portal home.",
            "Portal home 200 means full success always.",
            "Skip federated servers in drills.",
            "Import never needs databases.",
        ),
        _q(
            m,
            "**Backup** of **Portal content** directory without **relational** store backup. Recovery risk?",
            "**Inconsistent** item state versus database—coordinate backups per Esri recovery design.",
            "Content directory alone is always enough.",
            "Relational store is optional for hosted layers.",
            "File copy replaces WebGISDR always.",
        ),
        _q(
            m,
            "**Maintenance**: rebuild **search index** after disk move. Why?",
            "**Index path** and health—not only freeing disk.",
            "Search rebuilds automatically on reboot always.",
            "Delete search to save disk permanently.",
            "Index lives only in browser cache.",
        ),
        _q(
            m,
            "**Server Manager**: applying **cluster** patch order. Guidance?",
            "Follow **Esri** rolling/sequencing steps for multi-machine **Server**—not random reboots.",
            "Patch one machine forever; others follow eventually.",
            "Disable all nodes during patch.",
            "Server Manager patches Portal automatically.",
        ),
        _q(
            m,
            "**Portal Administrator** — changing **default user role** before a big onboarding. Risk?",
            "Unexpected **license** consumption and privileges—plan role defaults with licensing.",
            "Default role affects only usernames.",
            "Default role cannot assign licenses.",
            "Disable licensing checks during onboarding.",
        ),
        _q(
            m,
            "**WebGISDR** during **peak** hours: operational mistake?",
            "**Resource contention** and longer export—schedule in **maintenance** windows when possible.",
            "WebGISDR never uses I/O.",
            "Peak runs complete faster.",
            "Users never notice WebGISDR.",
        ),
        _q(
            m,
            "**LDAP** sync **schedule** and **load**: tuning?",
            "Balance **freshness** with **directory** and Portal load—very frequent sync can spike CPU.",
            "Sync every second is best always.",
            "LDAP sync never affects performance.",
            "Disable sync and use CSV only.",
        ),
        _q(
            m,
            "**Primary site administrator** password policy: where enforced?",
            "**ArcGIS Server** security and OS policy—not Portal password policy alone.",
            "Portal controls Server primary admin password.",
            "Primary admin never expires.",
            "Disable password policy for GIS.",
        ),
        _q(
            m,
            "**Maintenance**: **clear REST cache** after **service overwrite**. When **not** to?",
            "After **every trivial** layer toggle—excessive clearing **hurts** performance; clear when **definitions** change materially.",
            "Never clear REST cache.",
            "Clear REST cache every minute.",
            "REST cache clears itself hourly always.",
        ),
        _q(
            m,
            "**WebGISDR** **staging** folder full mid-export. Fix?",
            "Expand **staging** or redirect per guidance; incomplete export is not a valid restore point.",
            "Delete production content to free staging.",
            "Continue export without staging.",
            "Disable tile cache from export.",
        ),
        _q(
            m,
            "**Portal** **upgrade** + **WebGISDR** compatibility: check?",
            "Use **supported** backup/restore matrix for **source and target** versions—not assume any pair.",
            "WebGISDR works across any version gap.",
            "Upgrade before backing up always.",
            "Skip compatibility matrix.",
        ),
        _q(
            m,
            "**Disaster recovery**: **RTO** for Portal **search**. Factor?",
            "**Reindex** time and hardware—not only restore files.",
            "Search is instant after file restore always.",
            "Search does not affect RTO.",
            "Delete search in DR to meet RTO.",
        ),
        _q(
            m,
            "**Server Manager** **logs** directory rotation: why?",
            "Prevent **disk full** and preserve **forensics** capacity—not infinite verbose logging forever.",
            "Logs never grow.",
            "Delete logs without stopping services is always safe.",
            "Disable all logging for performance.",
        ),
        _q(
            m,
            "**Portal** **maintenance** message vs **read-only** mode (if used): difference?",
            "**Communication** vs **enforced** behavior—depends on product features and your procedures.",
            "Banner always makes Portal read-only technically.",
            "Read-only mode is the same as maintenance message.",
            "Maintenance message blocks databases.",
        ),
        _q(
            m,
            "**Backup** encryption keys **rotation**: WebGISDR destination?",
            "Update **automation** and **secrets** stores so scheduled exports do not fail silently.",
            "Keys never rotate.",
            "WebGISDR ignores encryption.",
            "Store keys in portal content directory only.",
        ),
        _q(
            m,
            "**Multi-machine Server**: **patch** one node; version skew. Risk?",
            "**Unsupported** mix—follow **ordered** patching to return to supported state.",
            "Version skew is safe for weeks.",
            "Secondary Server nodes can run a different patch version temporarily without impacting service delivery.",
            "Patch random nodes indefinitely.",
        ),
        _q(
            m,
            "**WebGISDR** **validation** script post-import: purpose?",
            "Catch **config** issues before declaring production cutover—not optional if your org requires it.",
            "If the WebGISDR import completes without errors, skip validation to shorten the cutover window.",
            "Skip validation to save time.",
            "Script fixes all issues automatically.",
        ),
        _q(
            m,
            "**LDAP** **SSL** cert rotation on directory: Portal action?",
            "Update **LDAP** **trust** / cert references in Portal **security** config.",
            "LDAP ignores TLS.",
            "Portal auto-pulls new certs without config.",
            "Disable LDAP SSL forever.",
        ),
        _q(
            m,
            "**Monitor** **agent** upgrade alongside Enterprise upgrade: note?",
            "Match **agent** and **Monitor** **server** compatibility per release notes.",
            "Agents never need upgrades.",
            "Monitor upgrade upgrades Portal automatically.",
            "Uninstall Monitor before Enterprise upgrade always.",
        ),
    ]

    # --- manage-content-users (26) ---
    rows += [
        _q(
            g,
            "To correlate **maps, apps, layers**, and **member** activity with **groups and roles**, where do you start in a typical Enterprise deployment?",
            "**Portal** **organization** reporting and item/member usage views; refine with **groups** and **custom roles**—Monitor does not replace portal entitlement and sharing views.",
            "ArcGIS Monitor item-level role mapping.",
            "Server Manager user activity by web map.",
            "Active Directory only for layer views.",
        ),
        _q(
            g,
            "**Administrative group** in Portal: what is it **not**?",
            "A substitute for **ArcGIS Server** **privileges** or **database** **sysadmin**—it governs **portal** administration features available to members.",
            "Grants Windows Domain Admin automatically.",
            "Replaces SAML configuration.",
            "Controls ArcGIS Server patch installation directly.",
        ),
        _q(
            g,
            "**Portal** **group** **owner** responsibilities include?",
            "Managing **membership** and **group** settings that affect **sharing** and **update** capabilities for items shared to the group.",
            "Owning all databases referenced by layers.",
            "Installing Web Adaptor updates.",
            "Replacing the Portal primary administrator account.",
        ),
        _q(
            g,
            "**Shared update** group: two **editors** **delete** the same **feature** near simultaneously. Typical outcome?",
            "**Last edit wins** at the service unless **versioning** workflows apply elsewhere—governance matters.",
            "Portal always merges edits automatically without conflict.",
            "Deletes are impossible in shared update groups.",
            "Portal queues concurrent delete operations in shared update groups to prevent simultaneous conflicts.",
        ),
        _q(
            g,
            "**Role** allows **publish** but **group** restricts **who can share** to the group. Effect?",
            "User may **publish** items they **own** but still cannot **share** into a **restricted** group without **membership/permissions**.",
            "Publish role overrides all group rules always.",
            "Groups only affect viewers.",
            "Sharing ignores group settings.",
        ),
        _q(
            g,
            "**Everyone (public)** sharing disabled org-wide; a **dashboard** must be public. Valid approach?",
            "Follow **policy** for **approved** public mechanisms or **exception** processes—not **workarounds** that violate governance.",
            "Use primary administrator credentials for public layers.",
            "Disable HTTPS for public content.",
            "Copy data to a personal cloud drive.",
        ),
        _q(
            g,
            "**Content** **dependency** report shows a **web map** references a **deleted** **layer** item. Who fixes?",
            "**Item owners** or **admins** repair **web map** layers—not automatic platform healing.",
            "Portal auto-repairs broken maps nightly.",
            "Server Manager restores deleted items.",
            "Restart Portal to fix references.",
        ),
        _q(
            g,
            "**ArcGIS** **token** embedded in a **shared** **dashboard** URL. Risk?",
            "**Credential** **exposure** and **reuse**—use **short-lived** tokens and **OAuth** patterns appropriate to clients.",
            "Tokens in URLs are safe if HTTPS.",
            "Tokens cannot be copied.",
            "Portal rotates URL tokens automatically.",
        ),
        _q(
            g,
            "**LDAP**-imported **group** mapped to a **custom role**. User removed from AD group overnight. What might happen?",
            "On next **sync**, portal **membership** and **role** may **change**—not always instant.",
            "AD removal is instant in Portal always.",
            "Portal never removes users automatically.",
            "LDAP sync is one-time only.",
        ),
        _q(
            g,
            "**WebContextURL** affects **collaboration** **invitations** how?",
            "Invitations and **trust** embed **URLs**—changing **WebContextURL** requires **updating** **collaboration** **connections**.",
            "Invitations auto-update when DNS changes.",
            "Collaboration ignores portal URL.",
            "WebContextURL only affects email footers.",
        ),
        _q(
            g,
            "**Administrative** **privilege** to **manage members** vs **manage security**. Typical split?",
            "**Member** lifecycle vs **security** **settings** (e.g., **SAML**, **LDAP**)—custom roles can separate duties.",
            "One role must do everything always.",
            "Security cannot be delegated.",
            "Any custom role with the Manage Organization Members privilege can configure SAML settings.",
        ),
        _q(
            g,
            "**Group** **tags** and **categories** for discoverability: limitation?",
            "They aid **search** and **organization**—they do **not** replace **sharing** rules.",
            "Tags make items public automatically.",
            "Categories enforce classification legally.",
            "Tags replace collaboration.",
        ),
        _q(
            g,
            "**Sharing** **update** capability on a **hosted** **layer** to a **group** of **contractors**. Compliance concern?",
            "**Data** **classification** and **contracts** may forbid **editing** for some users—**technical** sharing must match **policy**.",
            "Portal enforces legal contracts automatically.",
            "Update capability is always safe for contractors.",
            "Groups cannot contain external members.",
        ),
        _q(
            g,
            "**Portal** **Featured** **content** vs **group** **gallery**: difference?",
            "**Org-level** **highlights** vs **group** **focused** collections—different scopes for **defaults** and **discovery**.",
            "They are identical settings.",
            "Featured content replaces basemap gallery.",
            "Group gallery overrides org settings always.",
        ),
        _q(
            g,
            "**Usage** **by** **member** shows **high** **credits** **tools** use for one **user**. Governance?",
            "**Roles** and **privileges** limiting **premium** **capabilities**—not everyone needs **GeoAnalytics** access.",
            "Credits are untraceable in Enterprise.",
            "Usage reports are admin-only always.",
            "Disable reporting for privacy.",
        ),
        _q(
            g,
            "**Built-in** vs **enterprise** **logins** for the same **email**. Risk?",
            "**Duplicate** **identities** and **ownership** **confusion**—plan **cutover** and **mapping**.",
            "Portal merges them automatically.",
            "Built-in cannot coexist with enterprise.",
            "Email is not a unique key.",
        ),
        _q(
            g,
            "**OAuth** **app** **registration** for **Portal**—**redirect** **URI** list includes **localhost** for **dev** only. Production fails. Fix?",
            "Register **production** **HTTPS** **URIs** for the **client** **apps**—not **localhost** in prod.",
            "OAuth accepts any redirect without registration.",
            "Add `*` redirect for convenience.",
            "Disable OAuth for production apps.",
        ),
        _q(
            g,
            "**Group** **limit** per **organization** policy reached. Mitigation?",
            "**Consolidate** **groups**, **archive** **unused**, or **adjust** **policy**—technical **limits** are real.",
            "Unlimited groups in Enterprise always.",
            "Delete random users to free groups.",
            "Merge orgs without planning.",
        ),
        _q(
            g,
            "**Portal** **administrative** **activity** **log** vs **usage** **reports**: use case?",
            "**Audit** **who** **changed** **security** **settings** vs **how** **items** are **consumed**—different questions.",
            "Usage reports replace audit logs.",
            "Audit logs show map pan events.",
            "Disable both for performance.",
        ),
        _q(
            g,
            "**Collaboration** **workspace** **participant** **cannot** **see** **hosted** **layers** shared to the **workspace**. Check?",
            "**Sharing** **level** **and** **workspace** **membership** for those **items**—not only **connection** **status**.",
            "Collaboration shares everything automatically.",
            "Hosted layers cannot be collaborated.",
            "Workspace ignores sharing.",
        ),
        _q(
            g,
            "**Custom role**: **create** **groups** but not **delete** **groups**. **Owner** **leaves**. Issue?",
            "**Ownership** **transfer** **policy**—some actions require **owner** **or** **admin** **recovery**.",
            "Portal auto-assigns a new owner randomly.",
            "Groups without owners delete immediately always.",
            "Server Manager fixes portal group ownership.",
        ),
        _q(
            g,
            "**ArcGIS Server** **primary** **administrator** **password** **shared** with **ten** **publishers**. Problem?",
            "**Shared** **privileged** **credentials** **break** **auditability** and **security**—use **named** **accounts** **and** **roles**.",
            "This is a recommended pattern for speed.",
            "Primary admin is read-only.",
            "Publishers require primary admin password.",
        ),
        _q(
            g,
            "**LDAP** **filter** returns **service** **accounts** **with** **interactive** **logon**. Licensing impact?",
            "They may **consume** **named** **user** **slots** if **assigned** **roles**—**tighten** **filters**.",
            "Service accounts never sync to Portal.",
            "LDAP cannot return service accounts.",
            "Licenses ignore LDAP membership.",
        ),
        _q(
            g,
            "**Sharing** **to** **everyone** **(org)** vs **sharing** **to** **a** **group** **of** **the** **whole** **org**: nuance?",
            "**Org-wide** **visibility** **vs** **group** **capabilities** **(update, etc.)**—not always interchangeable.",
            "They are identical for all item types.",
            "Everyone sharing implies edit rights.",
            "Groups cannot span the org.",
        ),
        _q(
            g,
            "**Token** **expiration** for **embedded** **apps**: user sees **login** **loop** **at** **idle**. Developer fix?",
            "**Refresh** **tokens** **or** **silent** **renewal** **per** **OAuth** **best** **practices**.",
            "Set token lifetime to unlimited.",
            "Disable idle timeouts globally.",
            "Use primary admin token in embed.",
        ),
        _q(
            g,
            "**Portal** **groups** **used** **for** **licensing** **assignment** **via** **enterprise** **groups**: what must stay aligned?",
            "**IdP** **group** **membership**, **Portal** **sync**, **and** **license** **counts**—review **periodically**.",
            "Licensing ignores group membership.",
            "AD is authoritative for license billing only.",
            "Portal assigns licenses randomly from groups.",
        ),
    ]

    c = Counter(r[0] for r in rows)
    assert len(rows) == 100, len(rows)
    assert sum(c.values()) == 100
    assert c[d] == 34, c
    assert c[t] == 18, c
    assert c[m] == 22, c
    assert c[g] == 26, c
    return rows


if __name__ == "__main__":
    c = Counter(r[0] for r in get_extra_100_ops_scenarios())
    print(c, sum(c.values()))
