#!/usr/bin/env python3
"""
100 tricky scenarios aligned to EAEP Skills Measured themes (EIG segment weights 34/18/22/26):
Deploy, Troubleshoot, Maintain, Manage — Monitor, data stores, Portal, Web Adaptor, federation
(additional sites), authorization, airgap/offline, usage reports, Online↔Enterprise collaboration,
sharing, publishing/SDE/layer package access, troubleshooting.

Returns: (domainId, stem, correct, wrong1, wrong2, wrong3).

Distractor policy: eaep_distractor_design.py (on-domain wrong answers; plausible misconfigurations).
"""

from collections import Counter


def _q(domain, stem, c, w1, w2, w3):
    return (domain, stem, c, w1, w2, w3)


def get_extra_100_skills_scenarios():
    rows = []
    d, t, m, g = (
        "deploy-enterprise",
        "troubleshoot-enterprise",
        "maintain-support-enterprise",
        "manage-content-users",
    )

    # --- deploy-enterprise (34) ---
    rows += [
        _q(
            d,
            "An **air-gapped** environment cannot reach Esri license service or My Esri on the internet. What is required to **authorize ArcGIS Enterprise**?",
            "Use **offline authorization** workflows (license file / provisioning via supported offline procedures) per Esri documentation—not an online sign-in to My Esri from the deployment.",
            "Connect Portal to the internet temporarily on port 443 only.",
            "Skip authorization; Enterprise runs unlicensed in airgap mode.",
            "Copy any .prvc file from another org without matching your provisioning.",
        ),
        _q(
            d,
            "You add a **second federated ArcGIS Server site** for **raster analytics** while the **hosting server** remains on the original site. What must be true for hosted web layers?",
            "The **hosting server** assignment and data stores must support hosted workflows; federated **additional** sites serve their registered roles—verify each site’s role and registration.",
            "Any federated site automatically becomes hosting server.",
            "Second site cannot federate if one site is hosting.",
            "Raster analytics replaces hosting server always.",
        ),
        _q(
            d,
            "**Federation**: Portal trusts **Site A** (hosting) and **Site B** (image/raster). A publisher targets the wrong server URL in Pro. Symptom class?",
            "Items publish to the **site** and **stores** tied to that URL—align Pro connection with the portal and intended hosting/federated topology.",
            "Pro always publishes to all federated sites at once.",
            "Federation merges sites into one URL.",
            "Hosting server ignores which site you connect to.",
        ),
        _q(
            d,
            "After publishing a hosted feature layer, a user reports that queries return data but the data store status page shows the tile cache data store as the only registered store. An engineer suggests the tile cache store is sufficient for hosted feature layers. What is wrong with this assessment?",
            "The **relational** ArcGIS Data Store (hosted relational data)—not the tile cache alone for tabular hosted features.",
            "The spatiotemporal big data store only.",
            "File geodatabase on a share.",
            "The spatiotemporal big data store serves as the default backing store for all hosted feature layers.",
        ),
        _q(
            d,
            "**Tile cache** data store vs **relational** data store: when is the tile cache data store required?",
            "For **hosted scene layers** and **tile** caches that use the tile cache data store per your publishing workflow—not for every map service.",
            "For every feature service regardless of source.",
            "The tile cache data store is only required when the hosting server runs on a Linux operating system.",
            "Tile cache data store replaces relational always.",
        ),
        _q(
            d,
            "**Object store** registration: primary purpose in many Enterprise patterns?",
            "Large **attachments** and **blob** storage for hosted content where configured—not a substitute for relational or tile stores for all data types.",
            "Replace the relational data store entirely.",
            "Store only ArcGIS Online basemaps.",
            "Optional for all deployments without reading docs.",
        ),
        _q(
            d,
            "**Web Adaptor** name mismatch: external users resolve `gis.org.com` but WA binding uses a different hostname. Impact on OAuth?",
            "**OAuth redirects** and **certificates** must match the hostname clients use—align DNS, binding, and portal WebContextURL.",
            "OAuth ignores hostname if 443 is open.",
            "Users can always use IP addresses interchangeably.",
            "Web Adaptor hostname is cosmetic only.",
        ),
        _q(
            d,
            "Two **Web Adaptors** front the same Portal for **different URLs** (legacy vs new). What must OAuth apps include?",
            "**Every** client-facing hostname used in practice in **redirect URI** registrations—not only the newest name.",
            "The second Web Adaptor only handles static content; OAuth and admin REST must use the first WA.",
            "Second WA cannot share the same Portal.",
            "OAuth allows wildcards for all subdomains without registration.",
        ),
        _q(
            d,
            "**Airgap**: you cannot download **basemap** or **Living Atlas** content from the internet. Design choice?",
            "Provide **internal** basemaps/services and configure **utility** and **basemap** settings for disconnected operation—not default online endpoints.",
            "Portal automatically caches the entire world offline.",
            "Disable all maps in airgap.",
            "Living Atlas works without network if you enable offline mode in portal.ini.",
        ),
        _q(
            d,
            "**Offline authorization** file expires. Symptom before failure?",
            "License **validation** warnings and eventual **service** restrictions—renew provisioning via your approved offline process before expiry.",
            "Nothing changes until five years pass.",
            "Portal deletes all hosted layers on expiry day only.",
            "Airgap deployments never expire.",
        ),
        _q(
            d,
            "**Portal organization** settings: **featured content** and **basemap gallery** for a national agency—what are you configuring?",
            "Default **discovery** and **utility** experiences for members—not database storage locations.",
            "Physical paths to file geodatabases only.",
            "Firewall rules for 6443 only.",
            "SMTP relay for Living Atlas.",
        ),
        _q(
            d,
            "**Security** best practice: **HTTPS** everywhere for production Portal and Server. Exception philosophy?",
            "Lab/pilot may differ; production should terminate TLS properly and avoid mixed HTTP/HTTPS client flows without a documented reason.",
            "HTTP is fine internally always.",
            "Disable HTTPS on Web Adaptor to simplify OAuth.",
            "Use self-signed certs in production without distribution.",
        ),
        _q(
            d,
            "**ArcGIS Server** role: **Image Server** federated for **ortho** mosaics. Portal role?",
            "Specialized **server role** for raster; still **federated** and used per licensing—not the hosting server unless assigned as such.",
            "Image Server cannot federate with Portal.",
            "Image Server replaces base ArcGIS Server.",
            "Hosting server must be Image Server for all orgs.",
        ),
        _q(
            d,
            "**GeoEvent Server** as its own site federated to Portal. Deployment concept?",
            "Its own **ArcGIS Server** site/role for real-time; **not** a substitute for hosting server for standard hosted feature workflows.",
            "GeoEvent installs inside relational data store.",
            "GeoEvent replaces Web Adaptor.",
            "One machine cannot run GeoEvent and Server.",
        ),
        _q(
            d,
            "**Notebook Server** federated: data access failure from registered folder. First check?",
            "**Notebook Server** run-as account **OS permissions** to the path—not the author’s laptop permissions.",
            "Notebook uses Portal admin account always.",
            "Folders must be on the Portal machine.",
            "Disable HTTPS for UNC paths.",
        ),
        _q(
            d,
            "**Spatiotemporal big data store** vs **relational**: when is spatiotemporal appropriate?",
            "High-volume **observational** / **streaming** and **GeoAnalytics** patterns per docs—not every hosted feature layer.",
            "Replace relational for all hosted layers.",
            "Spatiotemporal stores only shapefiles.",
            "Required for all federations.",
        ),
        _q(
            d,
            "**Kubernetes** or **containers** (if used): admin takeaway for Enterprise?",
            "Follow **current Esri** release notes for **supported** topologies and operational differences—not generic container defaults alone.",
            "All Enterprise components run as one pod always.",
            "Containers eliminate Web Adaptor.",
            "Data store is always external to cluster without configuration.",
        ),
        _q(
            d,
            "**Reverse proxy** in front of **Web Adaptor**: what must preserve Portal behavior?",
            "**WebSocket**, **long polling**, **Host** header, and **timeout** rules per Esri reverse-proxy documentation.",
            "Proxies only need to forward TCP 443 blindly.",
            "Disable chunked encoding always.",
            "Portal never uses WebSockets.",
        ),
        _q(
            d,
            "**Multi-machine ArcGIS Server** site: **shared** config store. Wrong approach?",
            "Copying **VM disks** without supported **join**/**remove** steps—cluster state requires Esri procedures.",
            "Two config stores on USB drives.",
            "Each machine uses a local config store only.",
            "Hostname changes never affect clusters.",
        ),
        _q(
            d,
            "**Enterprise portal** **URL** used in **ArcGIS Online** **distributed collaboration**: what must align?",
            "**Reachable HTTPS** endpoints and **trust** between orgs—URLs embedded in collaboration **invitations**.",
            "Collaboration uses only internal 7443 between clouds.",
            "ArcGIS Online ignores Enterprise URLs.",
            "Collaboration requires identical license files.",
        ),
        _q(
            d,
            "**Federate** a **raster analytics** server that also hosts **image** services. Care?",
            "Clarify **roles**, **resources**, and **publishing** paths so users do not overload one site unintentionally.",
            "One federated site can only have one role.",
            "Raster analytics disables image services.",
            "Federation count is unlimited without performance impact.",
        ),
        _q(
            d,
            "**Portal** **privatePortalURL** for internal automation while **public** users use Web Adaptor. Why?",
            "Allow **trusted** internal processes to reach Portal without splitting **OAuth** public redirects incorrectly—configure per Esri guidance.",
            "privatePortalURL is only for email.",
            "Internal and external must use the same string always.",
            "Disable public URL when private exists.",
        ),
        _q(
            d,
            "**Authorize** additional **named users** after procurement. Where is entitlement applied?",
            "**Portal** license file / license management for the deployment—not only ArcGIS Online subscription if this is Enterprise.",
            "Email Esri support to activate users remotely without files.",
            "Named users come only from Active Directory count.",
            "Pro licenses ignore Portal file.",
        ),
        _q(
            d,
            "**Data store** **upgrade** order relative to Portal/Server: general principle?",
            "Follow the **documented** **compatibility** and **order** for your target release—not random component upgrades.",
            "Upgrade data store before backup always.",
            "Data store never upgrades independently.",
            "Skip version checks if Monitor is green.",
        ),
        _q(
            d,
            "**SDE** **enterprise geodatabase** registered with Server for **branch versioning** editing. Portal consideration?",
            "Appropriate **service** and **versioning** publishing patterns; hosted **branch** in relational store is a different model—do not conflate.",
            "Branch versioning requires ArcGIS Online.",
            "SDE cannot register with federated Server.",
            "Portal stores versions in the content directory.",
        ),
        _q(
            d,
            "**Web Adaptor** with **IWA** and **anonymous** layers on same URL: design tension?",
            "**Audit** and **identity** paths differ—ensure security design matches who must be identified vs public content.",
            "IWA applies to anonymous layers automatically.",
            "Anonymous disables IWA for the whole site.",
            "Two Web Adaptors are impossible on one IIS.",
        ),
        _q(
            d,
            "**Cloud** object storage registered for **caches** or **attachments**: Server must?",
            "Reach the **endpoint** with **valid** credentials from **each** node that participates—not only portal admin UI success.",
            "Cloud store uses portal password.",
            "One node credentials apply to all silently.",
            "Disable TLS for S3-compatible stores always.",
        ),
        _q(
            d,
            "**Disaster recovery** site with **airgap** restore: license file from production. Valid?",
            "License **entitlements** must match the **DR** deployment’s identity and **offline** renewal process—validate legal/procurement for DR copies.",
            "Any .lic file works on any machine.",
            "DR never needs a license file.",
            "Airgap DR uses ArcGIS Online licensing.",
        ),
        _q(
            d,
            "**Additional federated site** for **GeoAnalytics Server**. User runs **big** analysis jobs. Tuning axis?",
            "**GeoAnalytics** service and **data** **throughput** on that site and **spatiotemporal**/inputs—not Portal CPU alone.",
            "GeoAnalytics always runs on Portal machine.",
            "Increase only Portal search index.",
            "GeoAnalytics ignores spatiotemporal store.",
        ),
        _q(
            d,
            "**Portal** **security** settings: **TLS** cipher hardening. Client compatibility?",
            "Balance **security** baselines with **Pro**, **browsers**, and **mobile** support—test before production cutover.",
            "Disable TLS 1.2 for speed.",
            "Maximum ciphers work on all Windows XP clients.",
            "Cipher changes never affect OAuth.",
        ),
        _q(
            d,
            "**Web Adaptor** **sub-path** deployment (`/portal`, `/server`): common pitfall?",
            "**Path** and **proxy** rules must match **Portal** and **Server** **web adaptor** configuration—not only DNS.",
            "Sub-paths are unsupported entirely.",
            "Portal must always be at root `/` only.",
            "One WA cannot serve both Portal and Server.",
        ),
        _q(
            d,
            "**Federation** **validation** uses **administrative URL**. Certificate error. Fix class?",
            "**Trust** chain on the **Portal** machine for the **Server** admin cert—or use URLs that validate end-to-end.",
            "Disable cert validation in production.",
            "Federation ignores TLS errors if REST works in browser once.",
            "Use HTTP admin URL in federation only.",
        ),
        _q(
            d,
            "**ArcGIS Enterprise** **Builder** (Windows) vs **manual** install: when is Builder appropriate?",
            "Supported **base** **patterns** and **guided** install; complex multi-site may need **manual** steps per documentation.",
            "Builder is mandatory for all topologies.",
            "Builder cannot install Data Store.",
            "Manual install is unsupported.",
        ),
        _q(
            d,
            "**Additional** **federated** **ArcGIS Server** **site** for **raster** **analytics**; **Portal** already has a **hosting** **server**. What defines **which** **site** **receives** a **published** **service**?",
            "The **server** **URL** and **connection** **context** **in** **Pro**/**Manager** **aligned** **with** **that** **site’s** **role**—**not** **automatic** **routing** **by** **layer** **type** **alone**.",
            "Portal always sends raster jobs to the newest federated site.",
            "Hosting server must publish every service type.",
            "Federated sites share one configuration store URL for all publishes.",
        ),
    ]

    rows += [
        _q(
            t,
            "**ArcGIS Monitor** shows **green** for CPU on the hosting machine but **hosted** layers **timeout**. Best next correlation?",
            "**Relational data store** / DB metrics, **connection** pools, and **query** complexity—not Monitor CPU alone.",
            "If Monitor is green, blame the network only.",
            "Monitor replaces database tuning.",
            "Delete hosted layers to fix timeouts.",
        ),
        _q(
            t,
            "**Server logs** show **SSL handshake** errors **only** from **one** **subnet** to **6443**. Others OK. Focus?",
            "**Firewall** / **inspection** / **trust** differences for that subnet—not reinstalling Portal first.",
            "6443 must be open to the entire internet.",
            "Subnet issues mean DNS is always wrong.",
            "Disable HTTPS on Server.",
        ),
        _q(
            t,
            "**Portal** **usage** **report** shows **low** **views** while **Monitor** shows **high** **map** **service** **requests**. Plausible explanation?",
            "**CDN**, **cache**, **edge** hits, or **direct** REST use that **does not** increment portal item views the same way—reconcile metric definitions.",
            "Usage reports are always wrong if Monitor is high.",
            "Monitor counts portal logins only.",
            "Delete usage reporting.",
        ),
        _q(
            t,
            "**Federated** **second** site **Not reachable** in Portal after **GPO** change. First check?",
            "**Firewall** / **ports** / **DNS** between **Portal** and that site’s **admin** URL—not only user-facing 443.",
            "Second sites do not need admin reachability.",
            "GPO cannot affect GIS.",
            "Reinstall the second site without diagnosis.",
        ),
        _q(
            t,
            "**Web Adaptor** **502** during **peak**; **Server** **logs** clean. Suspect?",
            "**Proxy** **timeout** / **thread** limits / **upstream** queue—not only ArcGIS Server CPU.",
            "502 always means database down.",
            "Raise only the IIS application pool idle timeout on the Web Adaptor without reviewing proxy or upstream timeouts.",
            "Disable Web Adaptor logging.",
        ),
        _q(
            t,
            "**Interpret** **ArcGIS Server** **logs**: `Read timed out` to **relational** **data store** during **backup**. Interaction?",
            "**Backup** **I/O** or **locks** overlapping **peak** **editing**—coordinate windows.",
            "Read timeouts during backup mean the spatial reference of hosted layers no longer matches the map.",
            "Disable backups forever.",
            "Relational store never locks.",
        ),
        _q(
            t,
            "**Portal** **federated** **collaboration** **sync** **fails**; **443** **open**. Next?",
            "**Workspace** **settings**, **payload** **size**, **timeouts**, and **supported** **item** **types**—not only port checks.",
            "443 guarantees collaboration success.",
            "Collaboration uses SMTP only.",
            "Disable HTTPS for sync.",
        ),
        _q(
            t,
            "**User** has **Creator** but **cannot** **publish** **hosted** **layer**. **Logs** show **privilege** error. Common miss?",
            "**Custom** **role** or **organization** **policy** **blocking** **hosting**—verify effective privileges, not only user type name.",
            "Creator always implies unlimited hosting without checks.",
            "Hosting is controlled only by Pro license file.",
            "Disable Portal security to test.",
        ),
        _q(
            t,
            "**Monitor** **agent** **offline** on one **Server** **node**. Risk?",
            "**Blind** **spot** for that **node’s** health—restore agent and validate **cluster** **balance**.",
            "Offline agent means Server is down.",
            "Monitor agents are optional always.",
            "One node offline never affects HA.",
        ),
        _q(
            t,
            "**Troubleshoot** **performance**: **map** **service** **fast** at **small** **scale**, **slow** at **large** **scale**. Focus?",
            "**Data** **density**, **index**, **maxRecordCount**, **drawing** **complexity**—not only rebooting Portal.",
            "Scale only affects the basemap.",
            "Large scale always means network only.",
            "Set maxRecordCount to unlimited without impact.",
        ),
        _q(
            t,
            "**Logs** show **Invalid token** for **custom** **app** after **IdP** **rotation**. Check?",
            "**Metadata** / **signing** **certs** in **Portal** **SAML** config and **app** **refresh** behavior.",
            "Tokens never expire.",
            "Rotate only Windows passwords.",
            "Disable SAML for apps.",
        ),
        _q(
            t,
            "**Data store** **connection** **pool** **exhausted** in **verbose** **logs**. Symptom for users?",
            "**Intermittent** **query** **failures**—tune **pool**, **DB**, and **load**, not only Portal restarts.",
            "Pool exhaustion is harmless.",
            "Connection pool exhaustion only affects ArcGIS Pro desktop queries; web app REST calls bypass the pool.",
            "Delete connection pooling in PostgreSQL.",
        ),
        _q(
            t,
            "**Web Adaptor** to **Portal** works; **Server** **REST** through WA **404** for **wrong** **path**. Cause?",
            "**WA** **configuration** **context** for **Server** vs **Portal**—separate **adaptor** **instances** or **paths** per product.",
            "One WA path serves both identically always.",
            "404 means federation is broken always.",
            "Server has no REST endpoint.",
        ),
        _q(
            t,
            "**ArcGIS Online** **item** **referenced** in **Enterprise** **map** **fails** after **Online** **update**. Class?",
            "**External** **dependency** **change**—validate **layer** **URL** and **compatibility**, not only Enterprise uptime.",
            "Enterprise controls ArcGIS Online updates.",
            "Online layers never change.",
            "Disable Online layers in Enterprise.",
        ),
        _q(
            t,
            "**Monitor** **alert** **disk** **90%** on **tile** **cache** **volume**. Urgency?",
            "**Capacity** **before** **write** **failures** break **publishing**—plan **expansion** or **cleanup**.",
            "Wait for 100% full.",
            "Tile cache cannot fill disks.",
            "Delete relational store to free space.",
        ),
        _q(
            t,
            "**Federation** **trust** **expires**? Symptom pattern?",
            "**Server** **admin** **URL** **cert** or **password** **change** without **Portal** **update**—revalidate **federation**.",
            "Trust never expires.",
            "Federation uses only port 80.",
            "Portal auto-renews trust nightly without config.",
        ),
        _q(
            t,
            "**User** **upload** **.lpkx** to **Portal** **fails** with **generic** error; **same** **user** **publishes** **from** **Pro** **OK**. Direction?",
            "**Portal** **attachment** **limits**, **web** **upload** **path**, or **item** **type** **support**—compare Pro vs browser flows.",
            "Layer packages always upload like shapefiles.",
            "Portal rejects all packages.",
            "Disable HTTPS for uploads.",
        ),
        _q(
            t,
            "**ArcGIS Monitor** **alerts** **green** on **CPU**/**memory**; **users** **report** **slow** **editing** **only** on **one** **hosted** **layer**. **Server** **and** **Portal** **logs** show **long** **DB** **transactions**. Best isolation?",
            "**Layer**/**service**/**data** **path** **(indexes**, **locks**, **versioning**, **DB** **health**)**—not** **dismissing** **because** **Monitor** **host** **metrics** **look** **fine**.",
            "Monitor replaces database and GDB investigation.",
            "If CPU is low, the issue must be client GPU only.",
            "Slow editing always means network latency only.",
        ),
    ]

    rows += [
        _q(
            m,
            "**WebGISDR** **export** before **major** **upgrade**: why?",
            "**Recoverable** **point** if **upgrade** **fails**—follow **supported** **backup** **order** with **compatibility** **matrix**.",
            "Upgrades never fail if planned.",
            "WebGISDR is only for cloud.",
            "Skip backup if staging exists.",
        ),
        _q(
            m,
            "**Maintain** **stability**: **ArcGIS Monitor** **thresholds** for **memory** **leak** **pattern** on **Data Store** **host**. Action?",
            "Investigate **process** **growth** and **capacity** **plan**—not **silence** **alerts** indefinitely.",
            "Memory leaks fix themselves after reboot weekly.",
            "Disable Monitor alerts for data store.",
            "Add RAM without checking workload.",
        ),
        _q(
            m,
            "**Backup** **best** **practice**: **application-consistent** **database** **backup** for **relational** **data store** vs **file** **copy** **only**?",
            "Use **DB**-appropriate **backup** **tools** and **Esri** **guidance**—raw **file** **copy** **alone** risks **inconsistent** **recovery**.",
            "File copy is always enough for PostgreSQL.",
            "Stop SQL Server during file copy always.",
            "Relational store needs no backup if Portal is backed up.",
        ),
        _q(
            m,
            "**Upgrade** **ArcGIS Enterprise** **components**: **patch** **order** when **Portal** and **Server** **versions** **skew**?",
            "Bring the deployment back to a **supported** **combination** per **matrix**—not indefinite **skew**.",
            "Skew is safe if Monitor is green.",
            "Patch only what logs errors.",
            "Server version never matters to Portal.",
        ),
        _q(
            m,
            "**Optimize** **services**: **increase** **max** **instances** **everywhere**. Risk?",
            "**Memory** **pressure** and **diminishing** **returns**—tune **per** **service** **load**.",
            "Max instances should always be 999.",
            "Instances only affect legends.",
            "Portal controls all instance counts.",
        ),
        _q(
            m,
            "**Health** **check**: **Portal** **self** **diagnostics** **green** but **search** **stale**. Maintenance?",
            "**Rebuild** **search** **index** per **documentation** when **stale** **after** **migration** or **upgrade**.",
            "Search fixes itself daily always.",
            "Delete all items to refresh search.",
            "Search index lives only on clients.",
        ),
        _q(
            m,
            "**WebGISDR** **import** **to** **DR** **hostname** **different** **from** **prod**. Additional step?",
            "**Rename** / **rehost** **procedures** or **consistent** **URL** **plan**—**hostnames** **embed** in **trust** **flows**.",
            "Hostname never matters after import.",
            "Re-importing the Portal license file on the DR machine is sufficient to restore all federation trust flows.",
            "Change Windows display name only.",
        ),
        _q(
            m,
            "**Support** **ticket**: **nightly** **backup** **overlaps** **reindex**. Symptom?",
            "**Contention** **and** **long** **jobs**—**stagger** **maintenance** **windows**.",
            "Backups never lock files.",
            "Reindex is instant always.",
            "Run both at peak for efficiency.",
        ),
        _q(
            m,
            "**Maintain** **ArcGIS Monitor**: **agent** **version** vs **Monitor** **Server** **version**. Rule?",
            "Keep **compatible** **pairs** per **release** **notes**.",
            "Agents never update.",
            "Monitor Server upgrades all Enterprise components.",
            "Uninstall Monitor before patching Portal always.",
        ),
        _q(
            m,
            "**Restore** **test** **quarterly**: **Portal** **starts**; **hosted** **layers** **empty**. Miss?",
            "**Relational** **and** **content** **consistency** **at** **same** **recovery** **point**.",
            "Empty layers mean search index only.",
            "Restore content dir without DB always works.",
            "Hosted layers need no database.",
        ),
        _q(
            m,
            "**Service** **optimization**: **map** **service** **non-pooled** **site-wide**. Effect?",
            "**Resource** **semantics** **differ**—**misuse** **can** **exhaust** **processes**.",
            "Non-pooled is faster for all users always.",
            "Pooling is deprecated.",
            "Non-pooled instances only affect print and GP services; standard map services are unaffected.",
        ),
        _q(
            m,
            "**Backup** **retention** **vs** **compliance** **90** **days**. Gap?",
            "**Policy** **must** **match** **technical** **retention** **and** **immutability**.",
            "Retention is unlimited by default.",
            "Tape is always online and immutable.",
            "Delete backups when disk is full without policy.",
        ),
        _q(
            m,
            "**Upgrade** **staging** **environment** **hardware** **weak**. Conclusion from **load** **test**?",
            "**Non-representative** **staging** **misleads** **capacity** **planning**.",
            "Staging must equal prod or is useless always.",
            "Hardware never affects ArcGIS.",
            "Staging hardware only affects network throughput tests; CPU timeouts indicate client network issues.",
        ),
        _q(
            m,
            "**WebGISDR** **incremental** **misunderstanding**: admin expects **point-in-time** **DB** **rollback** **from** **incremental** **file** **copy** **alone**. Issue?",
            "**Database** **recovery** **model** **must** **support** **desired** **RPO**—coordinate **DBA** **and** **Esri** **restore** **steps**.",
            "Incremental copies replace transaction logs always.",
            "WebGISDR includes all DB history automatically.",
            "Rollback is always faster than backup.",
        ),
        _q(
            m,
            "**Patch** **OS** on **Server** **machines**: **GPO** **tightens** **ACLs** on **directories**. Symptom?",
            "**Service** **start** **failures**—**restore** **ArcGIS** **Server** **account** **ACLs** per **guidance**.",
            "GPO never affects ArcGIS.",
            "Reinstall Windows monthly.",
            "Delete config store when permissions break.",
        ),
        _q(
            m,
            "**Monitor** **dashboard** **for** **upcoming** **license** **expiry** (if configured). Purpose?",
            "**Operational** **visibility** **before** **hard** **failure**—still **validate** **provisioning** **process**.",
            "Monitor purchases renewals automatically.",
            "Licenses never expire in Enterprise.",
            "Disable license monitoring for airgap.",
        ),
        _q(
            m,
            "**Disaster** **recovery** **drill**: **services** **start**; **collaboration** **broken**. Scope?",
            "**Trust** **and** **URLs** in **DR** **context**—not **only** **service** **uptime**.",
            "Collaboration survives any restore automatically.",
            "DR never needs collaboration testing.",
            "Delete collaboration before DR.",
        ),
        _q(
            m,
            "**Maintain** **search** **index** **location** **move** **post** **upgrade**. Step?",
            "Update **portal** **index** **settings** **and** **rebuild** per **doc**—not **only** **copy** **files**.",
            "Index moves with copy-paste only.",
            "Search rebuilds on reboot always.",
            "Disable search to save disk.",
        ),
        _q(
            m,
            "**Procedural** **concept**: **clear** **REST** **cache** **after** **service** **overwrite**. When **not**?",
            "**Avoid** **constant** **clearing**—it **removes** **beneficial** **caches** **and** **adds** **load**.",
            "Never clear REST cache.",
            "Clear after every pan in the map.",
            "REST cache clears every minute automatically.",
        ),
        _q(
            m,
            "**Support** **case**: **GeoEvent** **memory** **leak** **suspected**. Evidence path?",
            "**Server** **logs**, **JVM** **settings**, **and** **Monitor** **trends** on **GeoEvent** **host**.",
            "GeoEvent has no logs.",
            "GeoEvent JVM heap is shared with Portal memory; only Portal JVM settings control GeoEvent allocation.",
            "Restart daily without investigation.",
        ),
        _q(
            m,
            "**Backup** **validation**: **restore** **to** **isolated** **VLAN** **monthly**. Why?",
            "Prove **recoverability** **separate** **from** **prod** **network** **assumptions**.",
            "Restore tests are optional if backups run.",
            "Isolated VLAN is the same as prod always.",
            "Skip DB restore in tests to save time.",
        ),
        _q(
            m,
            "**Pre** **upgrade** **health**: **WebGISDR** **export** **succeeds**; **relational** **data** **store** **validation** **warns** on **disk**. **Go**/**no-go**?",
            "**Resolve** **or** **mitigate** **data** **store** **capacity**/**health** **per** **Esri** **guidance** **before** **upgrade**—**not** **only** **Portal** **file** **backup** **success**.",
            "WebGISDR success alone authorizes upgrade regardless of store warnings.",
            "Disk warnings apply only to tile cache, never relational.",
            "Skip validation if staging passed once last year.",
        ),
    ]

    rows += [
        _q(
            g,
            "**Manage** **content** **sharing**: **web** **map** **shared** **to** **group**; **layer** **item** **owner** **left** **company** **without** **transfer**. Risk?",
            "**Broken** **dependencies** **or** **locked** **items**—**succession** **and** **admin** **recovery** **workflows**.",
            "Ownership auto-transfers to any group member.",
            "Portal deletes layers when users leave instantly always.",
            "Sharing ignores ownership.",
        ),
        _q(
            g,
            "**ArcGIS Online** **to** **Enterprise** **distributed** **collaboration**: **guest** **org** **receives** **updates** **daily** **only**. Expectation?",
            "**Sync** **schedule** **and** **workspace** **settings** **define** **latency**—not **real-time** **by** **default**.",
            "Collaboration is always real-time.",
            "Enterprise cannot receive from Online.",
            "Online collaboration requires identical license files.",
        ),
        _q(
            g,
            "**Usage** **reporting** in **Portal** for **which** **members** **used** **which** **premium** **tools**: use for?",
            "**Governance** **and** **chargeback** **visibility**—pair with **roles** **and** **licensing** **policy**.",
            "Usage reports replace ArcGIS Monitor.",
            "Monitor shows per-item user clicks in Portal UI.",
            "Premium tools have no meter in Enterprise.",
        ),
        _q(
            g,
            "**User** **cannot** **share** **web** **layer** **to** **group** **despite** **Publisher** **role**. Check?",
            "**Group** **membership** **and** **group** **capabilities** **(who** **can** **share** **to** **group)**.",
            "Publisher overrides all group rules always.",
            "Sharing is controlled only by item owner email.",
            "Disable groups to fix sharing.",
        ),
        _q(
            g,
            "**Publish** **from** **Pro** **using** **database** **connection** **file** **(.sde)** **referencing** **enterprise** **GDB**: **user** **gets** **002** **Insufficient** **privileges** **at** **publish**. Likely?",
            "**DB** **user** **privileges** **or** **connection** **authentication** **mismatch** **with** **what** **the** **service** **account** **needs**—not only Portal role.",
            "Portal Publisher fixes database grants automatically.",
            ".sde paths never affect publishing.",
            "Disable versioning to publish.",
        ),
        _q(
            g,
            "**Upload** **layer** **package** **(.lpkx)** **to** **Portal** **for** **hosted** **publishing** **blocked**; **role** **allows** **publish**. Cause class?",
            "**Organization** **settings**, **privileges**, **or** **supported** **workflows** **for** **package** **publishing**—validate **custom** **role** **capabilities** **and** **limits**.",
            ".lpkx is never supported in Enterprise.",
            "Layer packages bypass all security.",
            "Upload size is unlimited always.",
        ),
        _q(
            g,
            "**Content** **sharing** **to** **Everyone** **(public)** **disabled** **org-wide**; **dashboard** **must** **be** **public**. Process?",
            "**Policy** **exception** **or** **approved** **public** **channel**—not **primary** **admin** **workarounds**.",
            "Use primary admin for all public items.",
            "Disable HTTPS for public viewers.",
            "Copy maps to USB for public.",
        ),
        _q(
            g,
            "**Federation** **additional** **site** **listed** **in** **Portal**; **publishers** **choose** **wrong** **server** **connection** **in** **Pro**. Impact?",
            "Content **lands** **on** **unintended** **site** **or** **fails** **validation**—**train** **connections** **via** **portal** **URL**.",
            "Pro always picks hosting server automatically.",
            "All federated sites share one connection string.",
            "Federation hides extra sites from Pro.",
        ),
        _q(
            g,
            "**Collaboration** **from** **Enterprise** **(host)** **to** **ArcGIS Online** **(participant)**: **edits** **not** **appearing** **Online**. Check?",
            "**Sync** **direction**, **workspace** **content** **types**, **and** **schedules**—not **only** **‘connected’**.",
            "Online receives edits instantly always.",
            "Enterprise cannot send edits to Online.",
            "Collaboration requires matching usernames.",
        ),
        _q(
            g,
            "**Service** **capabilities**: **feature** **service** **with** **Sync** **enabled** **for** **offline** **Collector**; **org** **policy** **restricts** **export**. Conflict?",
            "**Sync** **implies** **downloadable** **data** **patterns**—**align** **policy** **with** **capabilities** **and** **sensitivity**.",
            "Sync works without exposing data.",
            "Disable Sync in the database only.",
            "Export policy overrides service capabilities always.",
        ),
        _q(
            g,
            "**Register** **cloud** **data** **store** **(S3)** **for** **publishing**; **access** **denied**. First alignment?",
            "**IAM**, **bucket** **policy**, **and** **ArcGIS** **Server** **credentials** **on** **all** **nodes**.",
            "Portal admin rights fix S3 always.",
            "S3 works without credentials in VPC.",
            "Disable HTTPS for S3 endpoints.",
        ),
        _q(
            g,
            "**Manage** **users**: **enterprise** **login** **with** **MFA** **works** **browser**; **Pro** **fails** **certificate**. Trap?",
            "**Trust** **chain** **for** **Pro** **on** **the** **workstation** **and** **any** **SSL** **inspection**—not **only** **Portal** **SSL**.",
            "Pro ignores enterprise certificates.",
            "MFA cannot work with Pro.",
            "Disable TLS for Pro only.",
        ),
        _q(
            g,
            "**Sharing** **update** **capability** **to** **external** **partners** **via** **group**; **data** **classification** **forbids** **export**. Technical vs policy?",
            "**Technical** **sharing** **does** **not** **override** **legal** **classification**—**design** **workflows** **accordingly**.",
            "Portal enforces legal classification automatically.",
            "External groups cannot have update capability.",
            "Disable HTTPS to block export.",
        ),
        _q(
            g,
            "**Item** **dependency** **chain**: **web** **map** → **hosted** **feature** → **related** **table** **service**. **Delete** **protection** **on** **layer**. Who is blocked?",
            "**Delete** **may** **still** **fail** **if** **maps** **reference** **item**—**dependency** **reports** **first**.",
            "Delete protection blocks only viewers.",
            "Maps auto-update when layer deleted.",
            "Server Manager deletes portal items automatically.",
        ),
        _q(
            g,
            "**Usage** **by** **item** **shows** **zero** **for** **embedded** **app** **in** **iframe** **on** **intranet**. Reason class?",
            "**Authentication** **and** **referrer** **context** **may** **not** **count** **as** **expected** **portal** **views**—**validate** **metric** **definitions**.",
            "iframes never count as usage.",
            "Usage only counts ArcGIS Online.",
            "Delete iframes to fix metrics.",
        ),
        _q(
            g,
            "**Authorize** **ArcGIS** **Enterprise** **named** **users** **after** **merger** **of** **two** **license** **files**. Risk?",
            "**Duplicate** **or** **conflicting** **entitlements**—**merge** **provisioning** **per** **Esri** **guidance** **and** **support**.",
            "Two license files always merge automatically.",
            "License files are additive without limit.",
            "Delete old file after copy without validation.",
        ),
        _q(
            g,
            "**Offline** **(airgap)** **content** **sharing** **workshop**: **trainers** **bring** **laptops** **with** **USB** **layer** **packages**. **Portal** **policy** **blocks** **uploads**. Balance?",
            "**Approved** **staging** **and** **scanning** **process** **or** **admin** **ingest** **paths**—not **bypassing** **security** **with** **shared** **passwords**.",
            "Disable antivirus for training week.",
            "Use primary admin account for all uploads.",
            "Airgap means no upload limits.",
        ),
        _q(
            g,
            "**Collaboration** **workspace** **direction** **Enterprise** → **Online** **for** **features** **only**; **attachments** **missing** **Online**. Check?",
            "**Supported** **content** **types** **and** **attachment** **sync** **settings** **for** **the** **workspace**.",
            "Attachments always sync with geometry.",
            "Online strips attachments for security always.",
            "Enable email for attachment sync.",
        ),
        _q(
            g,
            "**Custom** **role**: **create** **and** **manage** **groups** **but** **not** **assign** **licenses**. **User** **cannot** **create** **group**. Why?",
            "**Other** **privileges** **or** **org** **limits** **(max** **groups)** **may** **still** **block**—**check** **effective** **permissions** **and** **quotas**.",
            "Create group privilege works without any other check.",
            "The create group privilege is blocked by the org’s maximum group quota, not admin-level restrictions.",
            "Disable custom roles to fix.",
        ),
        _q(
            g,
            "**Publishing** **error**: **user** **has** **Editor** **not** **Creator**/**GIS** **Professional** **for** **hosted** **layer** **workflow**. Fix?",
            "**Assign** **user** **type** **that** **includes** **hosting** **privileges** **per** **your** **licensing** **model**—not **only** **a** **custom** **role** **name**.",
            "Editor always includes hosting in Enterprise.",
            "Custom role can grant hosting without user type.",
            "Hosted layers require only Viewer.",
        ),
        _q(
            g,
            "**Share** **as** **web** **layer** **from** **Pro** **to** **Portal**; **database** **data** **source** **uses** **OS** **authentication** **but** **Server** **service** **account** **cannot** **authenticate**. Align?",
            "**Service** **account** **model** **vs** **OS** **auth** **connections**—use **supported** **DB** **auth** **for** **publishing** **context**.",
            "OS auth always works if Pro works.",
            "Map service account must be the same as desktop user.",
            "Disable OS authentication globally.",
        ),
        _q(
            g,
            "**Portal** **group** **with** **update** **capability**; **member** **lacks** **edit** **on** **layer** **in** **map**. Often?",
            "**Layer** **capabilities** **(editing** **flags)** **and** **field** **permissions** **in** **the** **service**—not **only** **group** **membership**.",
            "Group update implies full schema edit always.",
            "Portal groups override service capabilities.",
            "Disable editing in Pro to fix.",
        ),
        _q(
            g,
            "**ArcGIS Online** **organization** **linked** **via** **collaboration**; **item** **owner** **in** **Online** **deleted**. **Enterprise** **workspace** **shows** **errors**. Recovery?",
            "**Item** **ownership** **and** **workspace** **repair** **per** **collaboration** **procedures**—not **automatic** **healing**.",
            "Online deletion instantly syncs to Enterprise always.",
            "Collaboration ignores item owners.",
            "Recreate user with same email to fix GUIDs automatically.",
        ),
        _q(
            g,
            "**Usage** **reports** **for** **compliance**: **who** **exported** **from** **hosted** **layer**. Available where?",
            "**Portal** **reporting** **and** **auditing** **features** **as** **documented** **for** **your** **version**—**design** **logging** **if** **not** **native** **per** **field**.",
            "ArcGIS Monitor shows per-user export clicks.",
            "Server Manager lists portal exports.",
            "Exports are never auditable in Enterprise.",
        ),
        _q(
            g,
            "**Federation** **of** **three** **sites**: **hosting**, **raster**, **GeoEvent**. **Map** **service** **published** **to** **raster** **by** **mistake** **needs** **to** **be** **hosted**. Fix?",
            "**Republish** **through** **correct** **connection** **to** **portal** **with** **hosting** **server** **context**—**items** **tie** **to** **originating** **site**.",
            "Move services between sites without republish.",
            "Portal moves items between federated sites automatically.",
            "Delete Portal to consolidate sites.",
        ),
        _q(
            g,
            "**Content** **lifecycle**: **deprecated** **web** **layer** **still** **referenced** **by** **twenty** **maps**. Process?",
            "**Communication**, **dependency** **report**, **and** **staged** **replacement**—not **silent** **delete**.",
            "Delete layer; maps fix themselves.",
            "Maps ignore broken layers silently always.",
            "Portal sends automatic deprecation alerts to all item owners via email when a layer is removed.",
        ),
    ]

    c = Counter(r[0] for r in rows)
    assert len(rows) == 100, len(rows)
    assert sum(c.values()) == 100
    assert c[d] == 34, c
    assert c[t] == 18, c
    assert c[m] == 22, c
    assert c[g] == 26, c
    return rows


if __name__ == "__main__":
    c = Counter(r[0] for r in get_extra_100_skills_scenarios())
    print(c, sum(c.values()))
